### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by kkcosmo** [higankanshi/xZune.Vlc#1]
Hi,
what are the changes of having English comments instead of Chinese?

**Comment by higankanshi** [comment]
There are no English comments yet.
Ummm...I am not good at English.
If you have any questions,ask me.

**Comment by kkcosmo** [comment]
I could translate them with google translate and common sense... but if you English is not that good maybe this is not helpful for you ^^

**Comment by higankanshi** [comment]
Ummm...Actually,a majority of Chinese comments are translated form VLC documents.
You can see the VLC documents.

**Comment by RobotWorgem** [comment]
ni hao what this？ cai zhazha！

**Comment by wuzhenda** [comment]
那么我们可以这样交流了，为啥叫xzune.vlc，有啥含义吗？

**Comment by higankanshi** [comment]
xZune.Vlc是为了xZune项目写的Vlc开源库。

xZune是正在进行的仿Zune风格的开源播放器，视频使用Vlc，音频有打算使用BASS，所以之后也许会封装一个xZune.Bass。

这些都有开源的打算，都是免费软件。

发自我的 Windows Phone

-----原始邮件-----
发件人: "Henry" <notifications@github.com>
发送时间: ‎2015/‎6/‎1 16:39
收件人: "higankanshi/xZune.Vlc" <xZune.Vlc@noreply.github.com>
抄送: "HIGAN" <higan@live.cn>
主题: Re: [xZune.Vlc] comments (#1)

那么我们可以这样交流了，为啥叫xzune.vlc，有啥含义吗？

**Comment by wuzhenda** [comment]
Yes,You did fix the z-order of the vlc-wpf problem.and you use c# 6.0,which cause many problems in vs2012.

**Comment by wuzhenda** [comment]
能把2个工程合起来吗，https://github.com/ZeBobo5/Vlc.DotNet，比较要出2分人力来维护一个项目，而且你也未必有很多时间。

**Comment by higankanshi** [comment]
其实使用Vlc.DotNet构建一个原生的WPF控件也很简单。
只要参考xZune.Vlc.Wpf.VlcPlayer
使用相应的libvlc_video_set_callbacks函数，设置视频解码回调
之后使用共享内存与InteropBitmap，用InteropBitmap呈现图像就可以了
封装xZune.Vlc只是为了xZune项目，自己封装的库使用起来更为得心应手

**Comment by wuzhenda** [comment]
恩，有空试试，关键这2个工程都是拿来用的，没看代码
