### ISSUE TITLE
Take snapshot of video

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#10]
It would be useful to have a function that returns a snapshot of the video (Like VLC Media Player)

**Comment by higankanshi** [comment]
It is easy to take a snapshot.
But I don't kown can we take a snapshot with smooth video

**Comment by sepehr1014** [comment]
Yes, we can easily take a snapshot in WPF and Win Forms, but I think using VLC functions may yield better results.

**Comment by sepehr1014** [comment]
VLC itself pauses for a second or so, then takes the snapshot. I think it finds a good frame in range (smooth)

**Comment by higankanshi** [comment]
Ok, I add "TakeSnapshot" method for VlcPlayer.

```CSharp
        /// <summary>
        /// Take a Snapshot
        /// </summary>
        /// <param name="path">Save folder</param>
        /// <param name="format">Picture Format</param>
        /// <param name="quality">Quality of JPG</param>
        public void TakeSnapshot(String path, SnapshotFormat format, int quality)
```

It's easy to use.

```CSharp
        player.TakeSnapshot(@"C:\Users\HIGAN\Desktop\", SnapshotFormat.PNG, 0);
```
a pic like "My DVD-8055-0.png" will be create in your Desktop.

**Comment by sepehr1014** [comment]
That's nice, thanks

**Comment by Luperco** [comment]
Hi, I'm trying to use the TakeSnapshot function to create some thumbnails to show in some kind of camera roll with all my video.
Anyway the snapshot doesn't happen as soon as you call the TakeSnapshot function. So how I know when the snapshot is ready?
Is there a way to have the snapshot in memory (something suitable to show in an <image>) ?
Thanks.

**Comment by higankanshi** [comment]
Take snapshot always happened in next frame rendering. There has no exist way to get a snapshot as sync method.
I can give you a advice, maybe we can use [EventWaitHandle](https://docs.microsoft.com/en-us/dotnet/api/system.threading.eventwaithandle) for make it as a async task, then we can await it to completed.
