### ISSUE TITLE
using in xaml cause vs to hang

### ISSUE THREAD

**Issue by mylady** [higankanshi/xZune.Vlc#101]
hi, there are some problems i  meet:

1.using vlcplayer in xaml cause vs to hang
2.using vlcplayer in elementhost in winform usercontrol  cause PropertyMetadata has been registered by VlcPlayer

Enviroment:
VS2013
TARGET:.NETFRAMEWORK 4,0
xZune.Vlc.16.03.31
xZune.Vlc.Lib.15.11.24
xZune.Vlc.Wpf.16.03.31

thx in advance

**Comment by higankanshi** [comment]
01.可能是由于多线程的 Image 控件导致的，我准备为该控件添加一些设计时的优化。
02.是由于我将重写的 PropertyMetadata 放到了构造方法里面，每次都会调用，但是仅需要调用一次，多次调用就会报错。
03.同上。

我正在修复，请稍等一下，VS 升级 2015 U2 升级崩了，打不开了。。。OTZ

**Comment by higankanshi** [comment]
修复好了，Nuget包的话，没有 VS 暂时生成不了，不过我试了一下，这次应该是OK了，也不会导致 VS 无响应了。

**Comment by mylady** [comment]
回复的好快...
我换了使用的方式暂时绕过了这个问题,顺便把问题改成了英文 -.-
多谢多谢,等你的更新

**Comment by Evilpaule** [comment]
Could you please write this in english? I want to follow this issue because i have the same.

**Comment by higankanshi** [comment]
This issue is fixed with new package.
