### ISSUE TITLE
VlcPlayer内部是否可以支持全屏?

### ISSUE THREAD

**Issue by mylady** [higankanshi/xZune.Vlc#103]
VlcPlayer没有提供FullScreen的操作,看了一下源代码在默认的模板里面直接用了自定义的Image控件,是为了保持视频的分辨率而没有对Stretch进行TemplateBinding吗?
目前我使用了Image控件的Stretch=Fill方式实现了全屏播放,是否VlcPlayer可以增加全屏的支持?
另外Wiki里的Image.Source的更新没有加Dispatcher.BeginInvoke :)

**Comment by higankanshi** [comment]
由于自定义的 Image 是个多线程控件，所以不能 TemplateBinding，会有线程安全问题，然后 Stretch 都是在代码里面修改的。

全屏播放的话，建议你直接用 NonStyle 的无边框窗口实现，因为由我来提供全屏的话，你是不能更改的，例如沉浸式的播放控制按钮，鼠标右键菜单之类的。

Wiki 我稍后就修正。

**Comment by mylady** [comment]
我的描述有点问题,
我的意思是在播放器的界面上,现在是为了保持比例,没有铺满当前绘制的Image控件
如果我需要让播放器的界面上充满了图像,也就是不需要保持比例,那就只能用Image控件自己绘制了
增加FullScreen的目的在这里 :)

**Comment by higankanshi** [comment]
VlcPlayer 也有 Stretch 属性，你可以将他设置为 Fill。

**Comment by mylady** [comment]
设置了没有用

**Comment by higankanshi** [comment]
唔，我应该是有在VlcPlayer的代码里面手动更新了才对...我现在在家，清明最后一天回学校，让我看看是什么原因...
自从换了多线程的Image之后，bug有点多...OTZ，唔，不过多线程也是必然的选择...慢慢修复吧...

**Comment by mylady** [comment]
没关系,慢慢完善
这个项目比那个VlcDotNet好多了,那破玩意连个Loop都不提供
我项目不忙的时候也可以提交个PR :)

**Comment by higankanshi** [comment]
![qq 20160404214755](https://cloud.githubusercontent.com/assets/9367842/14249968/e78d8452-faae-11e5-9ef8-dd89eecbe5b2.png)
我试过了 VlcPlayer 的 Stretch 工作很正常啊。这是 1920 x 1080 的视频。
```XAML
<wpf:VlcPlayer x:Name="Player" EndBehavior="Repeat" Stretch="Fill"/>
```

**Comment by mylady** [comment]
你是直接把vlcplayer放在界面上的吧?
我是在CustomControl里面动态实例化的,通过代码设置的Stretch

**Comment by higankanshi** [comment]
动态实例化？没有用 XAML？还是说用你自己的呈现控件？

**Comment by mylady** [comment]
在CustomControl的实例化的时候直接new了一个vlcplayer加到child里面了,因为不能在xaml里面直接放vlcplayer的bug还在,你现在有更新nuget吗?我可以去测试

**Comment by higankanshi** [comment]
额，最新的Nuget包应该已经解决了这个问题才对。我改了一下设计时的代码，让设计时不要构建多线程的Image。

**Comment by mylady** [comment]
我更新一下试试,稍后反馈

**Comment by mylady** [comment]
不好意思,笔记本坏掉了,要周五才到货新的,装好之后再测试

**Comment by mylady** [comment]
各种悲剧之后,终于可以进行测试了....
这个bug已经解决了,又发现了另一个...
