### ISSUE TITLE
MouseDoubleClick Event for the VLC.Player do not work 

### ISSUE THREAD

**Issue by tombby11** [higankanshi/xZune.Vlc#104]
When inserting a 
` <wpf:VlcPlayer x:Name="Player" MouseDoubleClick="Player_MouseDoubleClick"/>`

Mouse Double Click event is never triggered. 

In order to go around this problem I have to put another user controller to catch the double click like follows 

```
 <Grid>
        <StackPanel>
            <wpf:VlcPlayer x:Name="Player"/>
        </StackPanel>
        <UserControl x:Name="DoubleClickCatcher" Background="Transparent"  MouseDoubleClick="OnMouseDoubleClick"></UserControl>
    </Grid>
```

So can this be fixed ?

**Comment by higankanshi** [comment]
Maybe  you can set the background of VlcPlayer.

**Comment by tombby11** [comment]
I did not really understand what you mean ? what I am saying is that MouseDoubleClick for VlcPlayer does not work.

**Comment by higankanshi** [comment]
Yes, I mean if you set the Background property, It must not be null if you want to use mouse event, like:"MouseDoubleClick ".
```XAML
<wpf:VlcPlayer x:Name="Player" EndBehavior="Repeat" MouseDoubleClick="Player_MouseDoubleClick" Background="Transparent"/>
```
