### ISSUE TITLE
How to turn on subtitles

### ISSUE THREAD

**Issue by kmcginnes** [higankanshi/xZune.Vlc#108]
I see there is some code in place to have `SubtitleTrack` objects. Is there any way to turn these on?

**Comment by higankanshi** [comment]
There have two way to do it.
You can delete the "--no-sub-autodecete-file" in your VlcSettings, it will auto select sub file.

Or, you can use the Player.LoadMediaWithOptins(), use those options:
:sub-file=C:\sub.ass

**Comment by kmcginnes** [comment]
The subtitles I wish to show are embedded in the video file. I wish, also, to turn them on and off while the video is playing.

I'm guessing that is not an option at the moment?

**Comment by higankanshi** [comment]
I don't know about it.
 Maybe you can check the document of VLC.

**Comment by higankanshi** [comment]
I found some other apis about subtitles. It may help you to do it.
I'll add it later.

**Comment by kmcginnes** [comment]
That would be great. Thank you @higankanshi !

My need for this is not immediate. In fact, I'm hoping to convince my bosses that it is unnecessary at all. But I wanted to get the conversation started.

**Comment by higankanshi** [comment]
You can notice that a update have been committed to dev branch.
New subtitle APIs in VlcMediaPlayer:
```
Property              VlcMediaPlayer.Subtitle
Property              VlcMediaPlayer.SubtitleCount
Property              VlcMediaPlayer.SubtitleDescription
Method                VlcMediaPlayer.SetSubtitleFile
```

**Comment by kmcginnes** [comment]
Awesome! I'll check it out when I get a chance.
