### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#11]
There should be a property to set playback speed. A float for example with default value of 1 ...

**Comment by higankanshi** [comment]
Vlc support that?
If Vlc support it, we will support it.

**Comment by sepehr1014** [comment]
Yes it does. When playing a video file in VLC Media Player, there is "Speed" under "Playback" in the right click menu.

**Comment by higankanshi** [comment]
Ummm...I can‘t find a API in LibVlc about "Playback speed".

**Comment by sepehr1014** [comment]
Try `libvlc_media_player_set_rate`:
http://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#gaa81be3afb20eddedf7ae56e98d4b1e06

**Comment by higankanshi** [comment]
Ohhh...I see.
We have "VlcMediaPlayer.Rate" Property.

I will add it to "VlcPlayer" later.
