### ISSUE TITLE
Small improvements  to VlcPlayer.cs regarding Xaml initialization . 

### ISSUE THREAD

**Issue by tombby11** [higankanshi/xZune.Vlc#111]
Hello I have made small improvements to VlcPlayer class. 
Now  you can assign the lib path and vlcOptions directly from xaml.  
And there are also some few syntax fixes I mean 
Please see the attached filles where you can find the class and the xaml file with examples 
I have tried to commit the code directly but I could not . 
[Hotfix.zip](https://github.com/higankanshi/xZune.Vlc/files/217419/Hotfix.zip)

**Comment by higankanshi** [comment]
Thank for your contribution.
