### ISSUE TITLE
Audio playback stereo mode

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#12]
VLC Media Player has 4 options for audio stereo mode: Stereo, Left, Right, Reverse stereo. It would be nice to have them

**Comment by higankanshi** [comment]
Ok, I have added "AudioOutputChannel" property.

It's a enum.
```CSharp
    public enum AudioOutputChannel
    {
        Error = -1,
        Stereo = 1,
        RStereo,
        Left,
        Right,
        Dolbys
    }
```

**Comment by sepehr1014** [comment]
Will check it soon, thanks!
