### ISSUE TITLE
.Net 4.5 branch

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#13]
It seems the only reason this awesome project isn't getting enough attention and many people use the alternatives (which are not even close to this project in terms of features) is the use of C# 6 specific features. It cannot be opened in Visual Studio 2013 and VS 2015 is still on RC state. Although VS 2015 is set to be released in a week or so from now, requiring users to have .Net 4.6 installed on their machine is not practical for at least a year.
So I suggest you maintain a .Net 4.5 branch in parallel with the main branch (Like most other projects) so all developers can benefit from this great project ...

**Comment by higankanshi** [comment]
Actually, I'm traveling now.
My notebook computer has not VisualStudio 2013.

On this weekend, I'll continue this work.

This project has a fork by @kkcosmo .
The fork has .NET 4.5 and VisualStudio 2013 support.

**Comment by sepehr1014** [comment]
Thank you @higankanshi 
That fork is old, it doesn't have the latest commits.
Converting it to .Net 4.5 is not difficult, but then I think we'll have to apply any changes made to the project, to our local copy of it. It would be great if there were two identical versions with different framework versions.

**Comment by higankanshi** [comment]
I want to remove Winform support, Winform has many differences between WPF.
Winform Control use HWND to display video.
But WPF use InteropBitmap, It means we can have same experience.
And most people will use it on WPF not on Winform

**Comment by sepehr1014** [comment]
I couldn't agree more. This project's strength lies in its WPF control.

**Comment by kkcosmo** [comment]
@sepehr1014 , yes I did not merged the latest changes. I have not yet had the time to get a little bit deeper into git and how to best merge the changes I want from this rep
if @higankanshi removes the winform and goes down to .net4 there would be no reason for my fork, so that would be great for me too :)

**Comment by sepehr1014** [comment]
@kkcosmo I hope he does! Thanks for your efforts.

**Comment by higankanshi** [comment]
Ummm...maybe we can write a document or wiki for xZune.Vlc.
Would you want it?

**Comment by sepehr1014** [comment]
That would be nice too. But I think a .NET 4/4.5 branch and a longer read me file (project description) is more important. As I said in the first post, many developers (including my friends & workmates) abandon this project only because of its dependency on C# 6.

**Comment by higankanshi** [comment]
Ummmm...I see....
OK, it's easy to retarget to .NET 4.5 and C# 5.

About "ReadMe", I will rewrite it this day.
My English isn't good, but I will get a try.

**Comment by sepehr1014** [comment]
That would be awesome!
And about ReadMe, English is not my first language either, but I may be able to correct grammatical errors ...
And a beginner's question: I'm not much familiar with GitHub. If I want to suggest a change, do I have to fork the project?

**Comment by higankanshi** [comment]
You can create a Pull Request.
I will check your code.
If I think your changes is useful, I can agree your Pull Request.

**Comment by sepehr1014** [comment]
Ok, thanks

**Comment by higankanshi** [comment]
I have added a ReadMe and LICENSE file.
Ummm...If something was wrong, please tell me.

**Comment by higankanshi** [comment]
I have some News for it.
I have added a branch for other DotNet versions.

xZune.VLC support:
>DotNet 2.0
>DotNet 3.0
>DotNet 3.5
>DotNet 4.0
>DotNet 4.5

xZune.VLC.WPF support:
>DotNet 3.5
>DotNet 4.0
>DotNet 4.5

Some features could have wrong, I have no test. If you have time, would you help me test it?

Some change of Stop method:
DotNet 3.5 and DotNet 4.5

VlcPlayer.Stop isn't a async method now, it will block thread.
```CSharp
vlcPlayer.Stop();
vlcPlayer.LoadMedia(@"C:\test.mp4");
vlcPlayer.Play();
```

If you want to stop media async:

For DotNet 3.5 and DotNet 4.0
VlcPlayer.BeginStop method
```CSharp
void LoadNewMedia(object sender, EventArgs e)
{
vlcPlayer.StopCompleted -= LoadNewMedia;
//load new media here
}
vlcPlayer.StopCompleted += LoadNewMedia;
vlcPlayer.BeginStop();
``` 

For DotNet 4.5:
VlcPlayer.StopAsync method
```CSharp
await vlcPlayer.Stop();
vlcPlayer.LoadMedia(@"C:\test.mp4");
vlcPlayer.Play();
```

**Comment by sepehr1014** [comment]
Great work, thanks.
I will extensively use and test .NET 4.5 version starting from now!
But I don't see the use of xZune.VLC support for .NET 2.0 when we can only use it in WPF and .NET 3.5+ ...

**Comment by higankanshi** [comment]
Ummm...You are right.

But you can use xZune.Vlc for .Net 2.0 in WinForm.
Create a WinForm Control by yourself...lol

**Comment by sepehr1014** [comment]
Oh I see!

**Comment by sepehr1014** [comment]
I think `VlcPlayer.Stop()` in .NET 4.5 should be `async` ...

**Comment by higankanshi** [comment]
We have this.
VlcPlayer.StopAsync()

**Comment by sepehr1014** [comment]
Oh, I see. I didn't have `DotNet45` in compilation symbols ...

**Comment by higankanshi** [comment]
I have pulled this branch to master.
