### ISSUE TITLE
Error on initialization

### ISSUE THREAD

**Issue by bbougot** [higankanshi/xZune.Vlc#14]
I'm trying to check out the project but I'm stuck very early. I've linked the two projects (xZune.Vlc and xZune.Vlc.Wpf) and my wpf:VlcPlayer is declared in my xaml. When InitializeComponent is launched, an exception related to OnInitialized method of VlcPlayer occurs.

InvalidOperationException: "Sequence contains no matching element"
More details in the screenshot:
![sans-titre-2](https://cloud.githubusercontent.com/assets/8962802/8552112/45de5950-24db-11e5-83f0-b0aff343fcf5.jpg)

Seems to be linked to the assembly, but I'm not really aware of what's going on.

**Comment by bbougot** [comment]
Allright, it seems to retrieve my project assembly, not the one of xZune.Vlc.Wpf. That's why there's obvisouly not any VlcSettingsAttribute in it.

**Comment by higankanshi** [comment]
You must set a LibVlcPath to use xZune.Vlc.

There are two ways to set it.
01.Add a VlcSettingsAttribute in your project's Assembly Info.cs.
Like this:
https://github.com/higankanshi/xZune.Vlc/blob/master/xZune.Vlc.Wpf.Sample/Properties/AssemblyInfo.cs
02.Set LibVlcPath property of VlcPlayer.
Like this:
<wpf:VlcPlayer LibVlcPath="..\..\..\LibVlc\"/>

**Comment by higankanshi** [comment]
I'll write a Quick Start in ReadMe later.

If you find any problems, please let me know 😉.

**Comment by bbougot** [comment]
Wonderful! Thank you so much! Great project :wink:
