### ISSUE TITLE
Embed wpf:VlcPlayer into a UserControl

### ISSUE THREAD

**Issue by bbougot** [higankanshi/xZune.Vlc#15]
Is it possible to embed the WPF player into a UserControl? I tried putting the WPF control into a grid, but it launch a new window (titled VLC (Direct3D Output)) instead.

![sans-titre-2](https://cloud.githubusercontent.com/assets/8962802/8557805/fd4994aa-24ff-11e5-8625-db9668d923e3.jpg)

**Comment by higankanshi** [comment]
Ummm...I don't know how did you do that.
Maybe you can see the sample.

**Comment by bbougot** [comment]
Issue solved! I was calling wpf:VlcPlayer.VlcMediaPlayer.Play() instead of wpf:VlcPlayer.Play() in my code-behind. We should review some access modifiers I guess. Anyway, that works perfectly! :wink:
