### ISSUE TITLE
Setting LibVlcPath property doesn't work

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#16]
If I add `[assembly: VlcSettings(@"..\..\..\LibVlc")]` to my AssemblyInfo.cs everything's fine, but if I want to set the controls property, it won't work and I get the exception `System.InvalidOperationException: Sequence contains no matching element`. Here's how I'm doing it:
`<vlc:VlcPlayer x:Name="mediaPlayer" LibVlcPath="..\..\..\LibVlc\" />`

**Comment by higankanshi** [comment]
I know this.
I will fix it later.

**Comment by higankanshi** [comment]
I have fixed it.
