### ISSUE TITLE
Provide LibVlc directory only before loading media

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#17]
Currently the directory of LibVlc should be specified before initialization and therefore should be hard-coded in the application. But that directory should not be needed before loading media and we should be able to specify the directory location at run-time. The main use would be to set different paths based on process CPU architecture. If the process is running in 64 bit mode, the property should point to the 64 bit version of LibVlc else it won't be initialized properly ...
So please initialize LibVlc before loading the media, not in control initialization.

**Comment by higankanshi** [comment]
I  see...
You are right...
I will have think about it.

**Comment by higankanshi** [comment]
Ok, I have added it.

You can set nothing.
Then use vlcPlayer.Initialize(libvlcPath,libvlcOption) Method to Initialize VLC.
