### ISSUE TITLE
Disable logger interface

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#19]
I may be missing something, but how can I disable the logger interface window from showing up? This also happens in Release mode.

**Comment by higankanshi** [comment]
Yes...I'll fix it later.

**Comment by TheThing** [comment]
@sepehr1014 I disabled the cmd/logger interface window from showing up using this:

```csharp
[assembly: VlcSettings(@"vlclib", new string[] { "-I", "dummy", "--dummy-quiet", "--ignore-config", "--no-video-title" })]
```

Took it from here: http://stackoverflow.com/questions/6001034/how-to-prevent-console-from-being-displayed-when-using-vlcs-dummy-interface

**Comment by sepehr1014** [comment]
@TheThing Thanks, it does the trick. Though I'm not comfortable editing `AssemblyInfo` to set the options of a library.

**Comment by higankanshi** [comment]
I have handled it.

**Comment by marza91** [comment]
@TheThing @higankanshi @sepehr1014 I tried this today in my wpf application, but couldn't make it work. Tried to copy the above line into AssemblyInfo.cs, App.xaml.cs and MainWindow.xaml.cs, but the window still appears. Tried with a few different interface names, including dummy, rc and logger, but it seems like my configurations are ignored. Any help?

**Comment by marza91** [comment]
Sorry for bothering, I should have checked the sample code, decscibed how I did it it #230 for anyone looking for it later..
