### ISSUE TITLE
Change Volume

### ISSUE THREAD

**Issue by ludarous** [higankanshi/xZune.Vlc#2]
Hi,
is in xZune.VLc a chance to set a Volume?

Thanks for answer
Ludek

**Comment by higankanshi** [comment]
Sorry,I'm so careless that forgot this.
I'll add it later.

Thank for use xZune.Vlc

**Comment by ludarous** [comment]
Ok. Thanks a lot for your prompt answer.
Good luck with xZune.Vlc

Ludek

**Comment by higankanshi** [comment]
Ummm,xZune.Vlc is not perfect yet.
If you found any problems,please let me know 😊.

**Comment by ludarous** [comment]
I have already found some problems. I write them to different threads.

**Comment by higankanshi** [comment]
Ok...Now you can use those Properties:

VlcPlayer.Volume
//Set or Get audio's Volume
VlcPlayer.IsMute
//Set or Get audio's MuteStatus

And this Function:

VlcPlayer.ToggleMute
//Toggle audio's MuteStatus

**Comment by luhong** [comment]
Hm... IsMute doesn't seem to work.  My testing code is as follows:
`            vlcPlayer.IsMute = true;
            vlcPlayer.LoadMedia(new Uri("<a rtsp url>"));
            vlcPlayer.Play();
`
