### ISSUE TITLE
Winforms support

### ISSUE THREAD

**Issue by Dave-Thornton** [higankanshi/xZune.Vlc#24]
Have you dropped winforms support. Does this now only work with WPF ?

**Comment by higankanshi** [comment]
If you want to use LibVlc in WinForm, you can use Vlc.DotNet project, or you can create a control by yourself by using xZune.Vlc core library.
WinForm control is easy to create, you can try it.

>Vlc.DotNet : https://github.com/ZeBobo5/Vlc.DotNet
