### ISSUE TITLE
是否能提供一个winform版本？

### ISSUE THREAD

**Issue by AioRos85** [higankanshi/xZune.Vlc#25]

**Comment by higankanshi** [comment]
由于WinForm的呈现原理和WPF完全不一样，所以有些WPF适用的特性WinForm无法提供，WinForm适用的特性WPF无法提供，所以移除了WinForm的支持，如果你想在WinForm上使用LibVlc，可以使用VLC.DotNet项目，或者基于xZune.Vlc构建一个WinForm控件，在WinForm上是很简单就可以做到的
