### ISSUE TITLE
There is a problem with the aspect ratio!

### ISSUE THREAD

**Issue by MozzieMD** [higankanshi/xZune.Vlc#27]
I did a fast sample to test it, and got a video 16:9, in classic media player it's 16:9 in xZune.Vlc it's transformed to 16:10 why? Well maybe 16:9.5, it's annoying, is there a way to keep aspect ratio?

**Comment by higankanshi** [comment]
It is Vlc's issue, I found it too.
When I got a Decode Context of 1920x1080, it always give me 1920x1200.
Don't worry about it, extra part is transparent.

**Comment by MozzieMD** [comment]
Yeah, but you get vertical black lines like in 2005

**Comment by higankanshi** [comment]
Vertical black lines?
Can you take a screenshot?

**Comment by MozzieMD** [comment]
http://i.imgur.com/ahGgVGW.jpg , the video is 720x400

**Comment by higankanshi** [comment]
Ummm...OK...I will try fix it later.

**Comment by MozzieMD** [comment]
Sure, take your time, and thanks )

**Comment by higankanshi** [comment]
I'm sorry to be late.

You can see #32 .

>I got it.
>I think the size we got with VideoFormatCallback is SAR(Sample Aspect Ratio).
>Actually, we need DAR(Display Aspect Ratio) .
>``` DAR = PAR x SAR ```
>So we need PAR(Pixel Aspect Ratio), but I can't find it in libvlc.

**Comment by higankanshi** [comment]
>New developments here!
>I try to fix it, it seem work fine now.

>You can try it.

>if SAR != DAR, it will try to get a correct aspect ratio, then it will stop media, and play it with correct  aspect ratio.

>If you think it is work fine, you can close this issue

**Comment by MozzieMD** [comment]
can't test it right now
