### ISSUE TITLE
未來將有計畫會在NuGut上提供安裝嗎?

### ISSUE THREAD

**Issue by jaelys** [higankanshi/xZune.Vlc#28]

**Comment by higankanshi** [comment]
NuGet包的话，会有一些问题需要解决，xZune.Vlc依赖于LibVlc库，如果将这些LibVlc库打包进去，就会导致NuGet包比较重，如果不打包LibVlc库，其它的版本LibVlc可能与xZune.Vlc有兼容问题。

**Comment by jaelys** [comment]
請問目前的xZune.Vlc 依賴的LibVlc 版本號區間為多少? 可以直接從VLC官方的使用嗎，還是說此專案中的VLC是另外編譯的?

**Comment by higankanshi** [comment]
xZune.Vlc 可以根据不同的版本来载入不同的功能，但是如果你在调用了超过版本的函数与功能，就会抛出函数没有载入的异常。
xZune.Vlc 提供了一个LibVlc组件，这里面的LibVlc是专门为xZune.Vlc编译的，提供了一些拓展功能，目前是与DVD菜单的鼠标交互，这些拓展功能在 https://github.com/higankanshi/xZune.Vlc/wiki/Compile-VLC-for-xZune.Vlc 中有说明，这篇Wiki也提供了如何为xZune.Vlc编译LibVlc的方法。

**Comment by higankanshi** [comment]
如果你不需要拓展功能的话，也可以直接使用官方的 LibVLc

**Comment by jaelys** [comment]
剛測試了一下2.0.6 LibVlc 發現讀取rtmp流時會出現開啟失敗的問題，令請教您如何關閉Debug console窗口的命令為何?

**Comment by higankanshi** [comment]
试试这个，另外，请问你在使用的时候遇到过 #29 的 issue 吗？
```CSharp
            Initialize(libVlcPath, new[]
            {
                "-I", "dummy", "--dummy-quiet", "--ignore-config", "--no-video-title", "--no-sub-autodetect-file"
            });
```

**Comment by jaelys** [comment]
使用LibVlc 2.0.6 時無法開啟rtmp流。LibVlc2.2.0時可以，但之前我採用Vlc.DotWPF時2.0.6可以正常運作，另#29 issue目前在我的環境中未遇到過，我的開發環境Win10 net4.6 64bit


兩種設置都無法關閉 Debug console窗口

Initialize(libVlcPath, new[]
            {
                "-I", "dummy", "--dummy-quiet", "--ignore-config", "--no-video-title", "--no-sub-autodetect-file"
            });

[assembly: VlcSettings(@"..\..\libvlc", new[]
            {
                "-I", "dummy", "--dummy-quiet","--ignore-config", "--no-video-title","--file-logging","--logfile=log.txt","--verbose=2","--network-caching=1000","--file-caching=1000"
            })]

**Comment by higankanshi** [comment]
我没有具体测试过RTMP流视频，不知道你具体是什么原因。
我在封装库的时候，版本控制应该和官网的文档一致才对。

另外关于设置参数，你可以参考VLC的官方WIKI或者文档。
