### ISSUE TITLE
On close exception, TaskCanceledException

### ISSUE THREAD

**Issue by MozzieMD** [higankanshi/xZune.Vlc#29]
When i close the app i get TaskCanceledException here:
`
public void Display()
        {
            if (Application.Current != null)
            {
                Application.Current.Dispatcher.Invoke(new Action(() =>
                {
                    Image.Invalidate();
                }));
            }
        }
`

On Closing i dispose like this:

`
await VlcPlayer.StopAsync();
VlcPlayer.Dispose();
`

**Comment by higankanshi** [comment]
Ummm...I test sample again, but it work fine.
You needn't stop media on closing, media will auto stop on disposing.

**Comment by MozzieMD** [comment]
ok i will stop without stopasync and see!

**Comment by MozzieMD** [comment]
now without stopasync got same exception but here: 
`private void SetTime(TimeSpan time, bool setVlcTime)
        {
            _setVlcTime = setVlcTime;
            Dispatcher.Invoke(new Action(() => SetValue(TimeProperty, time)));
        }`

**Comment by higankanshi** [comment]
Where did you use the Time Property?

**Comment by MozzieMD** [comment]
nowhere, ain't this a background work when video plays?

**Comment by higankanshi** [comment]
Ummm...yes, time property will be changed when you play a media.
But on disposing media will be stopped, time property also will not change.

You can build the Sample, and have a try.

**Comment by MozzieMD** [comment]
well my sample is the same, and this exception happens not always maybe you just didn't saw it!

**Comment by MozzieMD** [comment]
i did pause() before disposing will see if will help!

**Comment by higankanshi** [comment]
Ummm...Disposing after stopped, and stopping after paused...
You can see Stop method, stop will wait for pause...and dispose will wait for stop...

Ummmm...Maybe dispose isn't necessary...When you closed app, all resources will be released.

**Comment by yosualie8** [comment]
Hi MozzieMD i get that same error too, and fix it by using the vlc library that higankashi provide in the repo. If you use another vlc library that error will came out when you close the app, if you insist to use another version of library then you can stop the player first and then close you application 1 sec later after it stopped using timer.

**Comment by MozzieMD** [comment]
well i stopped to dispose it before closing, like @higankanshi said, works fine...
