### ISSUE TITLE
Problem with Stop

### ISSUE THREAD

**Issue by Manu1985** [higankanshi/xZune.Vlc#3]
Hello.

I use the fork and It seems that player.VlcMediaPlayer.Media.Stop() is not working. The application freezes if I use it. I had a look on it, but I can't find a mistake. 

Can you have a look on it?

**Comment by higankanshi** [comment]
Ok，I'll reply you later.

**Comment by higankanshi** [comment]
I got it.
There is a problem when stop a VlcMediaPlayer.
I attach decode callback, LibVlc will cause deadlock when stop media player, so we need pause media before stop, and wait for last frame decoding over.

I add a Method "xZune.Vlc.Wpf.VlcPlayer.Stop()" for stop media player.

```CSharp
        public void Stop()
        {
            VlcMediaPlayer.Pause(); //pause media player.
            context.Dispose();
            VideoSource = null;

            System.Threading.Tasks.Task.Run(() =>
            {
                System.Threading.Thread.Sleep(100); //wait for last frame decoding over.
                VlcMediaPlayer.Stop();
            });
        }
```

xZune.Vlc isn't perfect yet, if you have any problem, please let me know.

**Comment by Manu1985** [comment]
Thanks for the fast help. That is working.

If I try to load and play new media after a stop the applications is also freezing.

player.Stop();
player.LoadMedia(new Uri("http://xxxx"));
player.Play();

**Comment by higankanshi** [comment]
I try this.
I changed "Stop" method and "Play" method.

Remove decode callback when stopping media.
Attach decode callback when playing media.

It work well. App would not freeze...now...maybe?

Also, you can demand any functional requirements.

**Comment by Manu1985** [comment]
I tried it, but the app freezes.

My only requirement is playing streams in native WPF. It should be possible to stop the actual stream and load a new stream.

I tried two different ways:

This is the first way. If I click the button, the app freezes.
```C#
    public partial class MainWindow : Window
    {
        VlcPlayer player = null;

        public MainWindow()
        {
            InitializeComponent();
            player = new VlcPlayer();
            grid.Children.Add(player);
            player.LoadMedia(new Uri("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));
            player.Play();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            player.Stop();
            player.LoadMedia(new Uri("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));
            player.Play();
        }
    }

```
This is the second way.
```C#
    public partial class MainWindow : Window
    {
        VlcPlayer player = null;

        public MainWindow()
        {
            InitializeComponent();
            player = new VlcPlayer();
            grid.Children.Add(player);
            player.LoadMedia(new Uri("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));
            player.Play();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            player.Stop();
            grid.Children.Remove(player);
            player = null;
            player = new VlcPlayer();
            grid.Children.Add(player);
            player.LoadMedia(new Uri("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));
            player.Play();
        }
    }
```
This is working with the changed of "Stop" and "Play" method. Only if I click very fast the app crashes.

**Comment by higankanshi** [comment]
Ummm...I see...

You know...in "Stop" Method, I make thread sleep. Media will stop after 100 Millisecond in other thread.

```CSharp
player.Stop(); //TimeOffset 0
player.LoadMedia( ... ); //TimeOffset < 100, this time, the old media is not stopping.
player.Play(); //the new media request play without the old media stopped.
```

I want to find a better way to stop media.

**Comment by higankanshi** [comment]
Ok...
Now I changed "Stop" method to a asynchronous method.

You can use "async/await" keyword to make new media playing after old media stopped.
Like this:
```
        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            await Stop(); //wait for media stopping, it will spend about 50ms.
            player.LoadMedia(@"E:\Video\NFS11-2.mp4");
            player.Play();
        }
```

By the way, you can only use "LoadMedia" method, because the method will auto stop the old media.

Before I found a better way to stop media, I think there is one way to load new media.

**Comment by Manu1985** [comment]
I have a Window_Closing Event:
```C#
        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            player.Stop();
        }
```
Sometimes the app crashes with a KERNELBASE.DLL error. I think it could be the same problem.

**Comment by higankanshi** [comment]
You can release all vlc resources in this Event.
You will not get crashes when window closing.

```CSharp
        private async void MainWindow_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            await player.Stop();
            player.VlcMediaPlayer?.Media?.Dispose();
            player.VlcMediaPlayer?.Dispose();
            ApiManager.ReleaseAll();
        }
```

**Comment by Manu1985** [comment]
Thanks for the help. If I use player.VlcMediaPlayer.Dispose(); the app freeze. It seems to be the EventManager.Dispose();

**Comment by Manu1985** [comment]
Loading and playing new stream works very well. But I have a Problem with the async closing event. The app crashes sometimes when closing it.

I have added a 
```C#
Console.WriteLine("xxx"); 
```
after 
```C#
await Player.Stop();
```
 and there is no output in the VS console. What can be the problem?

**Comment by Manu1985** [comment]
I think it is a Problem of the async in the Closing event. 

This is working fine.
```C#
        private async void Button_Click2(object sender, RoutedEventArgs e)
        {
            await player.Stop();
            if (player.VlcMediaPlayer.Media != null)
            {
                player.VlcMediaPlayer.Media.Dispose();
            }
            //if (player.VlcMediaPlayer != null)
            //{
            //    player.VlcMediaPlayer.Dispose();
            //}
            ApiManager.ReleaseAll();
        }
```
If I use the Player.VLCMediaPlayer.Dispose(); the app freeze or crash.

But if it is comment out everything is working fine now.

**Comment by higankanshi** [comment]
Ummm...I can't reappear this problem.

```CSharp
        private async void Button_Click2(object sender, RoutedEventArgs e)
        {
            await player.Stop();
            if (player.VlcMediaPlayer != null)
            {
                player.VlcMediaPlayer.Dispose();
            }
            ApiManager.ReleaseAll();
        }
```
This is working fine in my project.

Maybe you can rebuild "xZune.Vlc.Wpf.Sample", I changed some code.
If you would not get crashes when window closes, all are working fine.

**Comment by higankanshi** [comment]
Well...you are right...I find a problem in xZune.Vlc.VlcMediaPlayer.Dispose()

ReleaseMediaPlayerFunction will release the event manager, after this operation the event manager's pointer is a invalid pointer, so it will crash with EventManager.Dispose().

But ReleaseMediaFunction will not release the event manager, so we should release it by ourselves.

```CSharp
        protected void Dispose(bool disposing)
        {
            if (disposed)
            {
                return;
            }
            
            HandleManager.Remove(this);
            ReleaseMediaPlayerFunction.Delegate(InstancePointer); //Release player and event manager.
            InstancePointer = IntPtr.Zero;

            EventManager.Dispose(); //dispose event manager.

            /*Free functions here.*/

            disposed = true;
        }
```

It can be...

```CSharp
        protected void Dispose(bool disposing)
        {
            if (disposed)
            {
                return;
            }
            
            HandleManager.Remove(this);
            //EventManager.Dispose(); //we need not release the event manager by ourselves.

            /*Free functions here.*/

            ReleaseMediaPlayerFunction.Delegate(InstancePointer); //Release player and event manager.
            InstancePointer = IntPtr.Zero;
            EventManager.SetReleased(); //make the event manager know the pointer has released.
            EventManager.Dispose(); //release the event manager's other resources.

            disposed = true;
        }
```

Now, I add VlcPlayer.Dispose() method, we can release player with this method.
It's easy to use.

```CSharp
        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            player.Dispose();
            ApiManager.ReleaseAll();
        }
```

**Comment by Manu1985** [comment]
Thanks for the info. I will try it.

**Comment by higankanshi** [comment]
Thanks for use xZune.Vlc, Good luck!
If you found any other problems,please let me know 😊.

**Comment by Manu1985** [comment]
In my test app it is working perfect now. Thanks for your great help.

I have a feature request but I will open a new issue for this.
