### ISSUE TITLE
Send cookies header

### ISSUE THREAD

**Issue by MozzieMD** [higankanshi/xZune.Vlc#30]
So, i want to play a mp4 file from a server, the server requires a cookie to be set, is that possible?

**Comment by higankanshi** [comment]
Is Vlc support that?
 If Vlc support it, we will support it.

**Comment by MozzieMD** [comment]
vlc have option --http-cookie but i tried to add that and it doesn't seem to work! because you can add options after media load i think!

**Comment by higankanshi** [comment]
I see, I will add this function after 2 weeks.

**Comment by higankanshi** [comment]
I'm sorry to be late.

I try to fix it, you can use new method:
```LoadMediaWithOptions```

You can try it, if it still not work, you can try add options before VLC initialize.
