### ISSUE TITLE
StopAsync() 會卡住，並引起類似#29的問題

### ISSUE THREAD

**Issue by jaelys** [higankanshi/xZune.Vlc#31]
我修正了一下，不會造成卡住，結束時也不會發生類似#29的問題，但我好像Pull request失敗，無法給您參考
          await System.Threading.Tasks.Task.Run(() =>
            {
                while (_stopping)
                {

                }
            }).ContinueWith((a) =>
            {
                VlcMediaPlayer.Stop();

                if (_context != null) _context.Dispose();
                _context = null;
                
            });
            VideoSource = null;

**Comment by higankanshi** [comment]
唔，我已经修改了相关的代码，但是 await 之后和使用 ContinueWith 有什么区别么

**Comment by jaelys** [comment]
這部分是之前開發的經驗，嘗試了一下這種解法，至於區別可以參考說明，我的觀念不一定正確http://www.codeproject.com/Articles/1018071/ContinueWith-Vs-await

但目前我認為只是先暫時解決了上下文的問題(呼叫VLC底層方法時)，不會卡住，但#29的狀況，在Debug會中斷的情況下，還是會發生，我會再多花時間測試研究整個專案架構，希望能幫得上忙，看能不能找出真正的原因

**Comment by higankanshi** [comment]
现在 Stop 的问题就在于 VLC 内部 Stop 的时候，资源冲突引起死锁，如果使用 VLC 自己的渲染方式，例如使用 GDI 的句柄渲染，会由 VLC 自己处理这些资源冲突，但是现在，我们采用的是直接渲染到内存，这个过程是由我们做的，直接调用 Stop 就会导致 VLC 自己无法解决冲突，导致死锁。

我现在的解决方案只能是，先暂停，让渲染过程停下来，之后再停止，暂停之后资源就没有冲突了。

由于 VLC 问题实在有点多，目前我在尝试为 FFMPEG 封装一个完整的 .NET 解决方案。
FFMPEG 已经支持 UWP 也是为了 UWP 能使用 FFMPEG。

但是 VLC 这边暂时应该还不会停止维护， VLC 使用起来要比 FFMPEG 快捷方便。

**Comment by jaelys** [comment]
今天測試了一天，大概發現問題出在結束時，Dispose時，內部異步調用Pause時，未處理完成，程序已經先結束，無法正常進入
var asyncResult = action.BeginInvoke((aresult) =>
            {
                VlcMediaPlayer.Stop();
                if (_context != null) _context.Dispose();
                _context = null;

                Dispatcher.BeginInvoke(new Action(() => VideoSource = null));

                callback(aresult);
                action.EndInvoke(aresult);
            }, null);

也無法正常進行_displayCallbackHandle.Free();
就會發生system.Threading.Tasks.TaskCanceledException 在兩處，一處是#29的問題，一處是

private void SetPosition(float pos, bool setVlcPosition)
        {
            _setVlcPosition = setVlcPosition;
            Dispatcher.Invoke(new Action(() => SetValue(PositionProperty, pos)));
        }

這部分應該有改善的機會，回報給您參考一下，我這邊先修改成可運行的Code試試，但怕破壞了您的架構，所以我就先測試到都沒問題再回報給您^^，很棒的專案，加油
