### ISSUE TITLE
4:3 instead of 16:9

### ISSUE THREAD

**Issue by maximality** [higankanshi/xZune.Vlc#32]
Hello!
I have a network stream with ts container. Video resolution is 720x576. Everything works fine, but there is one problem: wrong aspect ratio (4:3 instead of 16:9). 
VLC for Windows opens this stream with correct aspect ratio. Screenshots attached.
I've tried "--aspect-ratio=16:9" in options, but no luck.
Any suggestions?
Thanks!
![VLC Player](https://cloud.githubusercontent.com/assets/5983656/9694637/3bf0e172-5363-11e5-9b7e-1b06d9646f58.PNG)
![WPF App with xZune.Vlc](https://cloud.githubusercontent.com/assets/5983656/9694661/6a37ca0a-5363-11e5-8cac-dcbd30800ebc.png)

**Comment by higankanshi** [comment]
Ummm...I haven't try TS container, can you give me your video?

**Comment by maximality** [comment]
@higankanshi sure, you can open this stream: http://31.128.138.97:8080

**Comment by higankanshi** [comment]
Ummm...I can't connect to this IP. You can take a breakpoint in `VideoFormatCallback` to see height and width.

**Comment by maximality** [comment]
@higankanshi 
Height and width are both correct there.
![Breakpoint](https://cloud.githubusercontent.com/assets/5983656/9705444/a455819e-54cd-11e5-9502-d5434e48f4cb.png)
![Result](https://cloud.githubusercontent.com/assets/5983656/9705446/ad3c2196-54cd-11e5-8464-96df516ffb1c.png)

**Comment by higankanshi** [comment]
Ummm...Wait! 
720/576 = 5/4 = 1.25
720/540 = 4/3 = 1.33
720/405 = 16/9 = 1.78

Are you sure resolution is true?

**Comment by maximality** [comment]
@higankanshi you're right, but resolution is right.
Think it has something to do with non-square pixels?

**Comment by maximality** [comment]
@higankanshi http://dveo.com/downloads/TS-sample-files/San_Diego_Clip.ts found a stream for you. try it with your wpf player and with standalone vlc player

**Comment by higankanshi** [comment]
I got it.
I think the size we got with VideoFormatCallback is SAR(Sample Aspect Ratio).
Actually, we need DAR(Display Aspect Ratio) .
```DAR = PAR x SAR```
So we need PAR(Pixel Aspect Ratio), but I can't find it in libvlc.

**Comment by maximality** [comment]
@higankanshi maybe libvlc_video_get_size will do its job?

**Comment by higankanshi** [comment]
I have try it, I got (0,0) with TS stream.
But it work fine with local file.

**Comment by maximality** [comment]
Maybe try to get size after a couple of seconds of getting the stream?

**Comment by higankanshi** [comment]
Ummm...I also try it. I got (0,0).
You can try it, I add some properties, like ``` Size```, ``` PixelHeight ``` and ``` PixelWidth ```.

**Comment by higankanshi** [comment]
New developments here!
I try to fix it, it seem work fine now.

You can try it.

if SAR != DAR, it will try to get a correct aspect ratio, then it will stop media, and play it with correct aspect ratio.

**Comment by maximality** [comment]
@higankanshi seems to be very unstable
![2015-10-11 17 46 41](https://cloud.githubusercontent.com/assets/5983656/10417321/2015fcfe-7040-11e5-94b8-eff5b177a366.png)

**Comment by higankanshi** [comment]
Ummm...I see...
Can I use your Stream Location for test?

**Comment by maximality** [comment]
@higankanshi i set my pc to retranslate this local signal
you can try it on http://91.123.93.218:8080

**Comment by higankanshi** [comment]
![Work fine](http://higan-wordpress.stor.sinaapp.com/QQ%E6%88%AA%E5%9B%BE20151011230702.png)

It work fine with the sample.

**Comment by maximality** [comment]
@higankanshi well, it does not seems to work for me. now i have no picture and sample even crashed at   Image = (InteropBitmap)Imaging.CreateBitmapSourceFromMemorySection(FileMapping, Width, Height, PixelFormat, Stride, 0);

**Comment by maximality** [comment]
i have win7 x64, target .net 4.0

**Comment by maximality** [comment]
in 
Image = (InteropBitmap)Imaging.CreateBitmapSourceFromMemorySection(FileMapping, Width, Height, PixelFormat, Stride, 0); 
width, height and stride were = 0

**Comment by higankanshi** [comment]
Ummm...I see...
Can I use your Stream Location again?

**Comment by maximality** [comment]
@higankanshi sure, i will not turn it off

**Comment by higankanshi** [comment]
I need some time to test it, please keep stream in one hour...

**Comment by higankanshi** [comment]
New developments here!

You problem is the SAR we get when stream video buffering is 0/0 or 1/1.
I try many ways to fix, finally I use LayoutTransform to do it.

Now, it seem work fine.

Because we changed the size of image, I think it would have some problem to interact with DVD menu by using mouse. I can not sure. Although I have modified the mouse mapping algorithm.

**Comment by maximality** [comment]
![2015-10-11 21 25 29](https://cloud.githubusercontent.com/assets/5983656/10418259/c1b81b14-705e-11e5-8425-06053a31ee30.png)

**Comment by higankanshi** [comment]
If you in Debug mode, you can see the Output Window, you can see information like this:
```
StateChanged : Stopped to Opening
StateChanged : Opening to Playing
Initialize Video Content : 720x576
Aspect Ratio : 720x576
SAR:64/45
Resize Image to 1024x576
```

**Comment by maximality** [comment]
First time, i loaded it and it was ok
```
StateChanged : Stopped to Opening
StateChanged : Opening to Playing
Initialize Video Content : 720x576
Aspect Ratio : 720x576
SAR:1/1
Resize Image to 720x418
```

Second time, i played it and it was bad (aspect ratio wrong):
```
StateChanged : Stopped to Opening
StateChanged : Opening to Playing
Initialize Video Content : 720x576
Aspect Ratio : 720x576
SAR:64/45
Resize Image to 1024x310
```

**Comment by higankanshi** [comment]
See your ```VideoDisplayContext.CheckAspectRatio``` method.

It should be:

```CSHARP
public Size CheckAspectRatio(VideoTrack track)
{
    if (!IsAspectRatioChecked)
    {
        uint width = track.Width, height = track.Height;
        var sar = 1.0 * track.SarNum / track.SarDen;

        if (track.SarNum == 0 || track.SarDen == 0)
        {
            return new Size(1, 1);
        }

        Debug.WriteLine("Aspect Ratio : {0}x{1}\r\nSAR:{2}/{3}", Width, Height, track.SarNum, track.SarDen);

        if (sar > 1)
        {
            return new Size(1.0 * sar * width / Width, 1.0 * height / Height);
        }
        else
        {
            return new Size(1.0 * width / Width, 1.0 * height / Height / sar);
        }
    }
    else
    {
        return new Size(1, 1);
    }
}
```

And add breakpoint at return Size.

**Comment by higankanshi** [comment]
I add more debug information.
Like this:
```
StateChanged : Stopped to Opening
StateChanged : Opening to Playing
Initialize Video Content : 720x576
Video Size:720x576
SAR:64/45
Scale:1.42222222222222x1
Resize Image to 1024x576
```

**Comment by maximality** [comment]
![2015-10-11 22 14 04](https://cloud.githubusercontent.com/assets/5983656/10418508/74f0525e-7065-11e5-95f2-0b7a6f9ba1b9.png)

**Comment by higankanshi** [comment]
`height` is wrong.
`height` should be 576.
And height == track.Height == 576

**Comment by maximality** [comment]
and how can we fix it?

**Comment by higankanshi** [comment]
what is the `track.Height`?
Is it 82?

**Comment by maximality** [comment]
It is "random". Every time i play video i see different values :smile:

**Comment by higankanshi** [comment]
Random...I think memory must conflict with other application.
I try to fix it, you can have a try.

**Comment by higankanshi** [comment]
Anything update?
Do you have try it?

**Comment by maximality** [comment]
Value is random, i don't know how to fix it :(

**Comment by maximality** [comment]
Yes sir, now it works correct!
Thank you!
