### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by yosualie8** [higankanshi/xZune.Vlc#33]
Hi higankanshi im using your wrapper library in WPF, the issues i have is memory leak. I run 9 instances in a single WPF form and stream from 9 different RTSP links, after 3 hours the memory usage raise from 400 MB to 750 MB and make the player hangs. Can you please resolve this issue? 

Thank you

**Comment by higankanshi** [comment]
Ummmm...About this performance issue....
I think you can take memory snapshot.
