### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by maximality** [higankanshi/xZune.Vlc#35]
Hello @higankanshi 
Your WPF implementation of libVlc uses almost 2x CPU time of the standalone VLC application.
How can we reduce this value?

**Comment by higankanshi** [comment]
I compared the sample and VLC, I don't think they have a big difference.

![CPU usage](http://higan-wordpress.stor.sinaapp.com/QQ%E6%88%AA%E5%9B%BE20151011173420.png)

**Comment by maximality** [comment]
@higankanshi i get a difference about 10-20% (VLC 20-25%, WPF sample 35-40%) in HD 720 h264 ts stream.

**Comment by MozzieMD** [comment]
Well i get 20% of CPU usage, so i wonder, is there an option to enable GPU acceleration ?

**Comment by higankanshi** [comment]
Maybe you can open this issue on https://github.com/videolan/vlc
