### ISSUE TITLE
Loop Video

### ISSUE THREAD

**Issue by coczero** [higankanshi/xZune.Vlc#37]
How would I go about looping a video?
I tried 
VlcPlayer.LoadMediaWithOptions(path, "repeat"); //and also --repeat, --loop and loop
VlcPlayer.Play();

But it doesnt work. Any help?

**Comment by fabianPas** [comment]
+1! Would love to have this! Actually, I really need it!

**Comment by Megagalatkikarea2** [comment]
Any news on this? I really need this too!

**Comment by higankanshi** [comment]
I have tried many ways...
If you can accept some cacophonies at end of video...
I can do it.

**Comment by coczero** [comment]
I'm fine with cacophonies as long as the video loops smoothly.

**Comment by higankanshi** [comment]
Some news here.
I add the EndBehavior property to VlcPlayer, you can set it to Repeat to loop the media.

BTW, Stop method is changed too.

I changed many other coeds, so you can try it first.
If it was no problem with it, I will update the release and Nuget package later.
