### ISSUE TITLE
Scale and Aspect Ratio properties not working

### ISSUE THREAD

**Issue by maximality** [higankanshi/xZune.Vlc#38]
Hello @higankanshi. When i try to change Scale and/or AspectRatio properties during playback, they don't work as supposed to.

**Comment by maximality** [comment]
For example, i want to scale video twice. ''vlcControl.VlcMediaPlayer.Scale = 2.0'' don't work, ''vlcControl.ScaleTransform = new ScaleTransform(2.0,2.0)'' don't work either

**Comment by higankanshi** [comment]
ScaleTransform  property is internal...
If you want to do it, I think RenderTransform is best way to change size.

**Comment by maximality** [comment]
RenderTransform resizes the whole element, making it overlay other elements, such as window title bar

**Comment by higankanshi** [comment]
ScaleTransform property is used for fix #32 , I need change the LayoutTransform after I get correct SAR.
We recommend using the RenderTransform  to replace operation which any change the video size .

**Comment by higankanshi** [comment]
You can also use the LayoutTransform. this will change the layout size not only render size.

**Comment by maximality** [comment]
Is there any way to change VIDEO size INSIDE the vlcControl element, keeping vlcControl size?

**Comment by higankanshi** [comment]
Ummmm...We used some different way to display video.
The image size what we get is fixed, we can't change it, on playing. Because the memory size is locked.

If you want to get it, I also only can change the Image Control's Size which in VlcControl.
Maybe I can create wrapper property to do it with a easy way later.

**Comment by maximality** [comment]
```public VideoDisplayContext(int width, int height, PixelFormat format)
        {
            IsAspectRatioChecked = false;
            Size = width * height * format.BitsPerPixel / 8;
            Width = (int)(width * scale);
            Height = (int)(height * scale);
            PixelFormat = format;
            Stride = width * format.BitsPerPixel / 8;
            FileMapping = Win32Api.CreateFileMapping(new IntPtr(-1), IntPtr.Zero, PageAccess.ReadWrite, 0, Size, null);
            MapView = Win32Api.MapViewOfFile(FileMapping, FileMapAccess.AllAccess, 0, 0, (uint)Size);
            Application.Current.Dispatcher.Invoke(new Action(() =>
            {
                Image = (InteropBitmap)Imaging.CreateBitmapSourceFromMemorySection(FileMapping, Width, Height, PixelFormat, Stride, 0);
            }));
        }
```
Something like this shoul do the job?

**Comment by higankanshi** [comment]
Now I add Aspect Ratio property for VlcPlayer...
You can set it to default , 16:9 , or 4:3...
