### ISSUE TITLE
Video filters - deinterlace, brightness, contrast 

### ISSUE THREAD

**Issue by ORRNY66** [higankanshi/xZune.Vlc#39]
hello,
It Is Possible to adjust the video filters: saturation, hue, brightness, etc ..
Thanks a lot.

**Comment by sepehr1014** [comment]
+1
This feature would be very useful

**Comment by higankanshi** [comment]
Ummmmm...I can't find any API in libvlc about it.
If we do it in xZune.Vlc, maybe we will get some performance issue.
