### ISSUE TITLE
Error if stream url could not be opened

### ISSUE THREAD

**Issue by Manu1985** [higankanshi/xZune.Vlc#4]
It would be great if payer.LoadMedia would cause an own error if the stream URL could not be opened ( for example the host is not awailable or the stream URL is not correct).

Is this possible?

**Comment by higankanshi** [comment]
Ummm...I see....

You can listen VlcMediaPlayer.EncounteredError event.
This event will be triggered when player get a Error.

**Comment by higankanshi** [comment]
I try VlcError.GetErrorMessage(), I got nothing but null.
I don't know how to get more information of error.
But log.txt has detailed information.

Ummm...I want to find a way to get error information.

**Comment by Manu1985** [comment]
I tried VlcMediaPlayer.EncounteredError event, but I didn't get any Errors. Do you have a short example?

**Comment by higankanshi** [comment]
It is easy to use.
Like this:

```CSharp
        VlcPlayer.VlcMediaPlayer.EncounteredError += VlcMediaPlayerEncounteredError;
        VlcPlayer.LoadMedia(new Uri("http://127.0.0.1")); //Load a invalid media
        VlcPlayer.Play(); //Play media. VlcMediaPlayerEncounteredError will be triggered when connection timeout.

        private void VlcMediaPlayerEncounteredError(object sender, EventArgs e)
        {
            //To do something here.
        }
```

Ummm... I think you must not have any code in "VlcMediaPlayerEncounteredError", it will not be triggered when you don't have any code.

**Comment by Manu1985** [comment]
I found the mistake in my code. It works now, but I did not get Information about the error.

**Comment by higankanshi** [comment]
I know that.
I also don't find a way to get Information of error.

But I think we can get it from Logs.

Now, I have some trouble for compiling LibVlc.
I will add some LogAPI for LibVlc later.

**Comment by sepehr1014** [comment]
Have you tried `libvlc_errmsg`?
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__error.html
https://www.videolan.org/developers/vlc/doc/doxygen/html/include_2vlc_2libvlc_8h.html

**Comment by higankanshi** [comment]
Actually, We have it.

```CSharp
VlcError.GetErrorMessage();
```

But it aways return null, I don't know why.

**Comment by sepehr1014** [comment]
Only an error message wouldn't be of much use in globalized applications. You can't even use a switch case and provide the translation since it may change in future versions.
If we good get an error code along with the message, that would be ideal!

**Comment by higankanshi** [comment]
But LibVlc has no ErrorCode API...
I don't know how to do that.

**Comment by sepehr1014** [comment]
You're right, I just checked the documentation.
I'm not sure, but I think error message are locale-specific. Aren't they?
If you can fix the null message issue and add a property to set the locale, it may give the error in the desired language.

**Comment by higankanshi** [comment]
I can't sure Message is localized.
But I can try it later, I will try it by C++.
By the way, I guess it is a thread's problem.
