### ISSUE TITLE
How to set fullscreen mode

### ISSUE THREAD

**Issue by Artem124Krsk** [higankanshi/xZune.Vlc#40]
Hi!

Is any function to set fullscreen mode?

I tried to load media with option:
```javascript
VlcPlayer.BeginStop((ar) =>
            {
                VlcPlayer.LoadMediaWithOptions(uri, "fullscreen"); // --fullscreen, :fullscreen
                VlcPlayer.Play();
            });
```
But nothing is going on.

And one more moment, when mediastate is Ended i trying to load another media but nothing in going on:
```javascript
void VlcPlayer_StateChanged(object sender, ObjectEventArgs<Interop.Media.MediaState> e)
        {
            if (e.Value == Interop.Media.MediaState.Ended)
            {
                VlcPlayer.BeginStop((ar) =>
                {
                    VlcPlayer.LoadMedia(nexturi);
                    VlcPlayer.Play();
                });
            }
        }
```

**Comment by higankanshi** [comment]
We recommend the fullscreen(Window) mode instead the fullscreen(Classic), you can set the MainWindow's WindowState to Maximized and WindowStyle to None to set fullscreen mode.
Because you can play controls and other controls in fullscreen(Window) mode.
