### ISSUE TITLE
COMException in VideoDisplayContext constructor

### ISSUE THREAD

**Issue by Vasto** [higankanshi/xZune.Vlc#41]
Hi,

I'm developing an application for CCTV monitoring. I've found your VLC wrapper to be the best one of all which I tried, btu unfortunately I've run into some issues recently. My requirement is to display image from at least several ip cameras. As far I was able to run 8 simultaneously without issues. However when I try to add next ones, I got the "System.Runtime.InteropServices.COMException (0x80070008): Not enough storage is available to process this command" exception in the VideoDisplayContext constructor while invoking Imaging.CreateBitmapSourceFromMemorySection() method.

Not sure what to do with it... Would be grateful for any advices.

**Comment by higankanshi** [comment]
How many memory did you use with 8 instances.
I think it has no enough memory to create share memory and memory map.

Ummm...I has no idea with it. But I will try to find some way to improve available memory.

**Comment by higankanshi** [comment]
You can see this http://stackoverflow.com/questions/507853/system-error-code-8-not-enough-storage-is-available-to-process-this-command

**Comment by Vasto** [comment]
Yeah, seems like a memory issue... With 8 HD streams I got something around 1GB memory usage which as far as I was able to figure out, seems to be close to the limit of x86 .Net applications. Unfortunately I have had no luck with the x64 version of VLC so far. It crashes oftenly in places where the x86 version runs ok...

**Comment by Vasto** [comment]
When using the library in a x64 scenerio with 64-bit version of VLC, which I guess could help me with a memory limitation, I sometimes get a following exception while player is loading a video stream:

A first chance exception of type 'System.OverflowException' occurred in mscorlib.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>
Unhandled exception
</Description>
<AppDomain>
Zebra.vshost.exe
</AppDomain>
<Exception>
<ExceptionType>
System.OverflowException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
</ExceptionType>
<Message>
Arithmetic operation resulted in an overflow.
</Message>
<StackTrace>   
   at System.IntPtr.op_Explicit(IntPtr value)
   at xZune.Vlc.VlcMedia.GetTracks()
   at xZune.Vlc.Wpf.VlcPlayer.VideoLockCallback(IntPtr opaque, IntPtr&amp;amp; planes)</StackTrace>
<ExceptionString>
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at xZune.Vlc.VlcMedia.GetTracks()
   at xZune.Vlc.Wpf.VlcPlayer.VideoLockCallback(IntPtr opaque, IntPtr&amp;amp; planes)</ExceptionString>
</Exception>
</TraceRecord>

**Comment by higankanshi** [comment]
I didn't have any test with x64 version.
Ummm...Maybe there are some wrong with it.

Ummmm...Yeah...We need do some change make it work with x64...Like Int32 to Int64, Intptr.....
You know interop with C++ need strict memory control...

**Comment by Vasto** [comment]
Thank you for the answer.
I would like to ask if there would be any chances for x64 support in the future?

**Comment by higankanshi** [comment]
I have some news about it.
Now we support x64.

I have some wrong with GetTracks...
Now it work fine on x64 platform.
