### ISSUE TITLE
Error in VS2015 XAML designer when selecting the player in the XAML

### ISSUE THREAD

**Issue by birbilis** [higankanshi/xZune.Vlc#46]
At MainWindow.xaml of .net 4.5 test project in VS2015, when clicking on <wpf:VlcPlayer x:Name="Player"/> in the XAML editor, I get in the designer area:

**NullReferenceException: Object reference not set to an instance of an object.**

StackTrace
at xZune.Vlc.Wpf.VlcPlayer.get_AudioOutputChannel()

**InnerException: None**

**Comment by birbilis** [comment]
I then have to close and reopen the XAML file (if I select other item in the XAML source it doesn't get fixed by itself, stays at the error state)

**Comment by higankanshi** [comment]
Ummm, in DesignTime VlcMediaPlayer is null...
if we want to fix it, we have to change all properties...

**Comment by higankanshi** [comment]
Thanks for cleaning my code...

**Comment by birbilis** [comment]
You're welcome

**Comment by birbilis** [comment]
Quick workaround is to add null checks to such properties, will see to it

However, I can make it work in the designer too. The idea is that the default constructor would call the initialization method with default params and get vlc library path from assembly attribute or with more priority from a property set at the component in the designer. Saw you already have such infrastructure.

If someone wants custom init when using the player programmatically they'd call a parametric constructor that would call the init params for them. Could even have some constructor with a boolean param to not do init at all

Existing code will pay some penalty for the extra init if they were constructing player and then initing

If the problem is that you need some native surface or something to pass to vlc, could use wpf event that the component is added to a peer to do there what's needed if it has been marked internally as autoinitializing.

Speaking of autoinitializing could even have such a property to turn this behaviour on/off

Will think of it when I look again at the code

**Comment by higankanshi** [comment]
if there has no dll in default path. it will throw exception... if we don't init it when default path has no dll... VlcMediaPlayer is null...

**Comment by birbilis** [comment]
Yep, it could catch that and ignore it silently at the default constructor.

**Comment by birbilis** [comment]
and code could check anyway for (VlcMediaPlayer != null). I'll see into adding such checks for starters so that it fails more gracefully in the designer

**Comment by birbilis** [comment]
added the VlcMediaPlayer checks for null so it doesn't throw the error in the designer anymore. 

Of course this is more of a workarround, since with a parameterless constructor that calls initialization routine it could also work inside the designer I believe (although I'm not sure what executable path it gets for "current process" when running in the designer - there is some code one can add to behave differently when running in the designer btw, think I have it somewhere under ClipFlair Studio's code [at http://clipflair.codeplex.com] if you search for designer). If I have time I'll look into it again
