### ISSUE TITLE
Callback for Media Loaded & "Preview" Once Loaded

### ISSUE THREAD

**Issue by Deadpikle** [higankanshi/xZune.Vlc#49]
Hey,

Just some questions on how to do things. 

1) Is there any sort of callback for when the media has finished loading? Currently, I'm using the `VlcMediaPlayer.Media.DurationChanged` event (after calling `LoadMedia`) to see when the media is finished loading, but this seems...not ideal.

2) Is there any way to make the video player show the first frame of the video once the video is loaded? I don't want to play the video until the user clicks the play button, but it would be nice if the user had some visual indication that the video was loaded. I suppose I could mute the video, play it for a split second, and then pause it as a workaround?

Thank you! :)

**Comment by higankanshi** [comment]
Ummmm...
01.StateChanged event maybe can do this.
After LoadMedia method...
NothingSpecial -> Opening -> Buffering -> Playing...

02.Ummmm...Maybe you can try NextFrame() method...
I'm not sure...you can have a try...

**Comment by Deadpikle** [comment]
Re:
1) I just decided to keep using DurationChanged, as I didn't want the video to auto play when it started, thus relying on the StateChanged event was not what I needed.
2) NextFrame() didn't seem to do the trick, unfortunately -- unless you've called `Play()`, the video player doesn't like responding to NextFrame(). So, in my application, whenever I load media, I mute the player, tell the player to Play after the `VlcMediaPlayer.Media.DurationChanged` event has been triggered, monitor states (as you suggested), then pause and unmute the video once the `Play` state has been triggered. Then I reset the video to time 0. This, although convoluted, seems to work.
