### ISSUE TITLE
Interactive DVD menu

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#5]
This project is great and we want to use it as part of a big project. Thought can you add mouse/keyboard interaction to the VLC control? Since it's just an image, you can't interact with DVD menus which is extremely important for a media player. All mouse/keyboard events should be hooked and passed to the media player.

**Comment by higankanshi** [comment]
Ummm...I see...
You know LibVlc used GDI and Hwdn to display video.
But xZune.Vlc don't need Hwdn, we use InteropBitmap and Share memory.

LibVlc also need Hwdn to listen Mouse/Keyboard events.

But we don't have Hwdn in WPF.

Ummm...I have a ideal now!
I need a DVD file for test.Do you have one?

**Comment by sepehr1014** [comment]
Also check https://microsoftdwayneneed.codeplex.com/ section "airspace". It implements some of the required functionality. The article: http://blogs.msdn.com/b/dwayneneed/archive/2013/02/26/mitigating-airspace-issues-in-wpf-applications.aspx
I do have DVD movies but 4.5GB is not easy to upload and they are copyrighted. I think you could easily create a DVD menu using Windows Movie Maker: http://windows.microsoft.com/en-us/windows-live/movie-maker or other free DVD menu makers: http://www.iskysoft.com/dvd-solution/dvd-menu-creator.html
Feel free to drop me a message if you get into trouble with DVD menus and I'll try to upload one.
BTW this is a really useful project and you've done a remarkable job. Keep up the good work!
And although I'm not much familiar with Interop and these things, I'll try to contribute as much as I can.

**Comment by higankanshi** [comment]
Thanks for your help,It's useful.

Actually,I want to add a "Invisible Window".
I'll set Hwnd of this window to LibVlc.

Then,hook Mouse/Keyboard Events, use the Win32API "PostMessage" to post Mouse and Keyboard message to this window.

LibVlc will get this message.

This is my idea.

**Comment by higankanshi** [comment]
By the way,I think the perfect solution is that write a plugin for LibVlc ,send Mouse/Keyboard message to LibVlc...

**Comment by sepehr1014** [comment]
Nice idea, keep me posted.
Since I'm no expert in LibVlc (my expertise is WPF itself!), I may not be able to help much in that area. But we are going to extensively use this project, so I'll report any issues we encounter and request features to further refine this project.
LibVlc has a lot of potential (despite the licensing issues in some countries)

**Comment by higankanshi** [comment]
Ummm...I tried it...but I have failed.
LibVlc seem not to handle Mouse/Keyboard Event.

```CSharp
            InteractWindow.Show(); //show InteractWindow
            VlcMediaPlayer.Hwnd = InteractWindow.Handle; //set Hwnd to LibVlc
```

then I clicked mouse or pressed a key on InteractWindow, but nothing happened.

Ummm...I try it on "xZune.Vlc.Form.Sample", also nothing happen.

Then I tested Vlc.DotNet ... also them.

I can't find a way to send Mouse/Keyboard Message...

I'll test it in Win32(C++/MFC) later, if you know something about it please tell me.

**Comment by higankanshi** [comment]
New developments here!

I try it in MFC...Ummm...
My DVD menu have some wrong, now xZune.Vlc.WinForm have mouse interaction.

But xZune.Vlc.Wpf still can't interact with DVD menu.

I think it is a issue of LibVlc.
LibVlc use Hwnd to display video and interact with mouse/keyboard.
Even if I set a Hwnd for LibVlc, Hwnd will not be used after I hook Decode Callback.

So, my idea is importance to realization.

Maybe we should change SourceCode of LibVlc to get a "Native Wpf Vlc Control with Interactive DVD menu".

**Comment by sepehr1014** [comment]
That would be very nice!

**Comment by sepehr1014** [comment]
You have created an invisible window, right? Can't we capture mouse/keyboard events from the WPF control, and simulate them toward that invisible window? For example on `KeyDown` event of the WPF control, we simulate that key press and pass it to our invisible window.
Just an idea though ...

**Comment by higankanshi** [comment]
But, LibVlc will not to handle this event form Hwnd after I hook Decode Callback.
So, we can't pass it to LibVlc.

**Comment by higankanshi** [comment]
I tried changed some code for LibVlc...
But I get some wrong in it.

Ummm...I tried cross-compiling on Linux and Win32CompileMSYS on Windows.

```Shell
make[2]: Entering directory '/home/home/vlc/win32/src'
  CC       fourcc_gen
/bin/sh: -I../../extras/package/win32/../../../src: No such file or directory
Makefile:3180: recipe for target 'fourcc_gen' failed
make[2]: *** [fourcc_gen] Error 127
make[2]: Leaving directory '/home/home/vlc/win32/src'
Makefile:2238: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/home/vlc/win32'
Makefile:2123: recipe for target 'all' failed
make: *** [all] Error 2
```

Something was wrong in this MakeFile.
 
```Shell
fourcc_gen: misc/fourcc_gen.c misc/fourcc_list.h ../include/vlc_fourcc.h
	$(AM_V_at)rm -f -- $@
	$(AM_V_CC)$(BUILDCC) -I$(srcdir) -o $@ $<
```
AM_V_CC = @echo "  CC      " fourcc_gen;
BUILDCC = 
srcdir = ../../extras/package/win32/../../../src

Ummm...
BUILDCC is nothing. I can't understand this.
```Shell
@echo "  CC      " fourcc_gen; -I../../extras/package/win32/../../../src  -o $@ $<
```

Ummm...MakeFile is too difficult to use...OTZ... 

If you can help me to compile this LibVlc(3.0.0-xZune), maybe we will success to handle this issue.

**Comment by sepehr1014** [comment]
Have you seen this topic?
https://forum.videolan.org/viewtopic.php?t=120579

**Comment by higankanshi** [comment]
Ummm...My problem is in Making Files not others.

**Comment by sepehr1014** [comment]
Have you read the documentation? https://wiki.videolan.org/Win32Compile/
This seems very much related to your error: https://forum.videolan.org/viewtopic.php?t=125663
https://trac.videolan.org/vlc/ticket/14500
https://forum.videolan.org/viewtopic.php?t=121234

**Comment by higankanshi** [comment]
Ummm...it look like this https://trac.videolan.org/vlc/ticket/14927

**Comment by higankanshi** [comment]
I make some progress with compiling.

I am successed to compile LibVlc(2.2.0-xZune).
I will test it later.After test,I will give you a reply.

**Comment by higankanshi** [comment]
Ummm...I have some exciting news about it.
Now, We can interact with DVD menu by using mouse.

I add some API for LibVlc
So you must be update your LibVlc to "2.2.0-xZune" to use it.

Now, I still have some problem on it.
Ex : Mapping the coordinates of the mouse and the video.
After I handle it, I will update xZune.Vlc

Ummm...But I don't add any keyboard API.

**Comment by sepehr1014** [comment]
Wow, it's nice to hear that you're making good progress.
And although keyboard interaction is not a "must", it would be great to have this feature.

Good Luck

**Comment by higankanshi** [comment]
Now you can interact with DVD menu by using mouse.
It will be working well with "Stretch", "StretchDirection", "HorizontalContentAlignment" and "VerticalContentAlignment",Ummm...maybe?
I don't have many test. You can help me to test it.

**Comment by higankanshi** [comment]
BTW, Kayboard API maybe can be added in later version.

**Comment by sepehr1014** [comment]
You may be able to use `libvlc_media_player_navigate` for keyboard interaction:
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#ga8fe3bb8a48af33a012040196b0953a93
Also check this out: https://mailman.videolan.org/pipermail/vlc-devel/2010-September/076414.html

**Comment by higankanshi** [comment]
Ok, Now we support "VlcPlayer.Navigate" Method now.

You can hook Keyboard event by yourself.
Then you can interact with DVD menu by using Keyboard.

**Comment by sepehr1014** [comment]
Thanks, that would be useful

**Comment by sepehr1014** [comment]
Since you've changed the source code of libvlc, we can't use official VLC Media Player libraries? Do we have to use custom-built libvlc?
The reason I'm asking is that our users have VLC Media Player installed, so we wanted to use that library ...

**Comment by higankanshi** [comment]
Yes, you must use our LibVlc(2.2.0-xZune), if you want to interact with DVD menu by using mouse.

You can only copy the ```libvlc.dll``` and ```libvlccore.dll``` in your users folder, don't need copy "plugins".

LibVlc(2.2.0-xZune) also work well with VLC(2.2.0).

**Comment by sepehr1014** [comment]
I see, is LibVlc(2.2.0-xZune) compatible with VLC 2.1.2 ?
And so we also need a 64 bit version of LibVlc to use in 64 bit processes.

**Comment by higankanshi** [comment]
No...LibVlc(2.2.0-xZune) must work with VLC(2.2.0 or Higher)...

If I remember correctly, you must have VLC(2.2.0 or Higher) to interact with DVD menu by using keyboard.
Because the VlcMediaPlayer.Navigate Method need LibVlc(2.2.0 or Higher).

>LIBVLC_API void libvlc_media_player_navigate  ( libvlc_media_player_t *  p_mi, unsigned  navigate) 

>Navigate through DVD Menu. 

>**Parameters**
>p_mi the Media Player
>navigate the Navigation mode  

>**Version**
>libVLC 2.0.0 or later

**Comment by higankanshi** [comment]
Ummm...I'm wrong...I don't that is LibVlc(2.2.0-xZune) compatible with VLC 2.1.2

Maybe you can have a try.

**Comment by sepehr1014** [comment]
Oh, So the plugins should be the same version too?
Sure, but I really think this project needs 64 bit version too. Don't you think so?

**Comment by higankanshi** [comment]
Maybe I can give you source code of LibVlc(2.2.0-xZune)
You can compile it by yourself.

Change the "media_player.c", "libvlc_media_player.h" and "libvlc.sym".
Then add dev string "xZune" to "configure.ac"
You can get it.

**Comment by sepehr1014** [comment]
Sure, thanks. But isn't it better to include it in the project too? Most new application run on 64 bit architecture ...

**Comment by higankanshi** [comment]
Yeah...compile 64bit is easy.
But I will only include LibVlc(2.2.0-xZune 32bit/64bit).

If I have more free time, maybe we can create a project for LibVlc-xZune.
Compile every version LibVlc for xZune.Vlc.

**Comment by sepehr1014** [comment]
Do we currently have LibVlc 2.2.0 64 bit in the project? I think it's just the 32 bit version.

**Comment by higankanshi** [comment]
I will compile it later.

**Comment by higankanshi** [comment]
I write a wiki for "[Compile VLC for xZune.Vlc](https://github.com/higankanshi/xZune.Vlc/wiki/Compile-VLC-for-xZune.Vlc)".

You can see it.
