### ISSUE TITLE
新的wpf项目只需要引用xZune.Vlc.Wpf和xZune.Vlc吗？还是要引进libvlc

### ISSUE THREAD

**Issue by fengwangjie** [higankanshi/xZune.Vlc#53]
新的wpf项目只需要引用xZune.Vlc.Wpf和xZune.Vlc吗？还是要引进libvlc 如何制定引用的libvlc的路径

**Comment by higankanshi** [comment]
新 WPF 项目需要引用 xZune.Vlc 与 xZune.Vlc.Wpf，LibVlc 库是 P/Invoke 方式进行互操作的，所以不需要加入项目引用，但需要保证运行目录下有 LibVlc 库(可以定制这个路径)。

详细请参考 readme  

>https://github.com/higankanshi/xZune.Vlc#0715  
>https://github.com/higankanshi/xZune.Vlc#quick-start

**Comment by fengwangjie** [comment]
thanks
