### ISSUE TITLE
Several destroy to create throw "System.AccessViolationException" 

### ISSUE THREAD

**Issue by fengwangjie** [higankanshi/xZune.Vlc#55]
我用wpf控件  窗体有5个视频控件  需要切换播放 每次切换需要销毁后重新创建 多次切换后 就出现  "System.AccessViolationException"

**Comment by higankanshi** [comment]
唔，请提供一下堆栈信息，让我确定异常出现在哪里。

**Comment by fengwangjie** [comment]
![image](https://cloud.githubusercontent.com/assets/8510914/11265242/d3aa3ba0-8ed5-11e5-8828-ed4f0783569d.png)

**Comment by fengwangjie** [comment]
上面的截图是有时候切换会出现 内部组件错误的提示。
下面的截图是出现操作错误内存的问题
![image](https://cloud.githubusercontent.com/assets/8510914/11265308/5916ee64-8ed6-11e5-94ff-bf273b36a801.png)

**Comment by fengwangjie** [comment]
我把xZune.Vlc.Wpf包装了下 通过url是否存在来调用播放
    private void VlcUrlChanged(string url)
        {
            try
            {
                if (!string.IsNullOrEmpty(url))
                {
                    InnerUserIndicateChanged(url);
                }
                else
                {
                    this.Message = "无图像";
                }
            }

            catch (Exception exception)
            {
                this.Message = exception.Message;
            }
        }

        private void InnerUserIndicateChanged(string url)
        {
            var uri = new Uri(url);
            vlc_palyer.LoadMedia(uri);
            vlc_palyer.Play();
        }

**Comment by higankanshi** [comment]
你是怎么切换播放器之间播放的？

**Comment by fengwangjie** [comment]
你 qq号多少？qq交流

**Comment by fengwangjie** [comment]
我qq 279905497
