### ISSUE TITLE
Embed LibVlc into NuGet package

### ISSUE THREAD

**Issue by birbilis** [higankanshi/xZune.Vlc#56]
I believe the xZune.Vlc NuGet package should contain the LibVlc folder with the native libraries (not the xZune.Vlc.Wpf - that one will grab it via xZune.Vlc package dependency)

Looking at NuGet Package Explorer (the free GUI tool for NuGet at http://npe.codeplex.com), it seems to have some option for adding Native Libraries too, but not sure if that one is for C++ projects or something related to Interop etc. 

Maybe could just drag-drop the LibVlc there under the "lib" folder it shows when you open the .nuspec file. Not sure if it can set the project to copy the LibVlc folder with those libs from the Packages folder NuGet makes at the solution level to the executable folder of one's project that uses the package (usually bin/Debug or bin/Release) as it does with the .net libs via the references it ads. Probably with the native libraries option it adds some build task, but still not sure if it can copy a subfolder or if it will lay all those dlls flat at the target .exe folder. Have to experiment and/or read some doc or ask on stackoverflow how this could be done

**Comment by higankanshi** [comment]
Ummmm...I can have a try.

**Comment by higankanshi** [comment]
I have added a new Nuget Package "xZune.Vlc.Lib".
You can install the xZune.Vlc.Lib to add LibVlc in your project.

Install [xZune.Vlc.Lib](https://www.nuget.org/packages/xZune.Vlc.Lib/)
```Powershell
PM> Install-Package xZune.Vlc.Lib
```

**Comment by birbilis** [comment]
So, shouldn't xZune.Vlc have a dependency to it? Not sure though if one can decide to skip a dependency.

**Comment by higankanshi** [comment]
Ummm...You can only install xZune.Vlc and xZune.Vlc.Wpf if you have libvlc.
xZune.Vlc.Lib is only provide a way to fast download libvlc.

**Comment by birbilis** [comment]
what I'm saying is that maybe it is logical for xZune.Vlc to have a dependency on xZune.Vlc.Lib. However some may not want NuGet to bring them all that stuff (they may have custom VLC version etc.), that's why I was wondering if one can select they want to skip some dependency at install or update of say xZune.Vlc.Wpf

Maybe best is to add extra packages xZune.Vlc.WithLib and xZune.Vlc.Wpf.WithLib, with the following dependency chain: xZune.Vlc.Lib <- xZune.Vlc.WithLib <- xZune.Vlc.Wpf.WithLib. Then one would be able to just use package xZune.Vlc.WithLib for say a console app or xZune.Vlc.Wpf.WithLib for a WPF app

BTW, does NuGet somehow manage to copy the VLC libs from the Packages folder to the EXEcutable folder?

**Comment by higankanshi** [comment]
Ummm...My logic is:
01.Not WPF and no libs
xZune.Vlc + xZune.Vlc.Lib

02.Not WPF and has libs
xZune.Vlc

03.WPF and no libs
xZune.Vlc + xZune.Vlc.Wpf + xZune.Vlc.Lib

04.WPF and has libs
xZune.Vlc + xZune.Vlc.Wpf

You can see. Whenever we need xZune.Vlc. So all depend on xZune.Vlc.

**Comment by birbilis** [comment]
Thing is that one cannot just add one package and bring in dependencies like that. You have an optional dependency. That's why I suggested adding two extra alternative packages that depend on the xZune.Vlc.Lib (in fact xZune.Vlc.WithLib would only depend directly on it and xZune.Vlc.Wpf.WithLib would depend indirectly, via its dependency to xZune.Vlc.WithLib)

then you'd have:

01.Not WPF and want default VLC libs
 xZune.Vlc.WithLib (will bring in xZune.Vlc.Lib via a dependency to it)

02.Not WPF and has custom VLC libs
 xZune.Vlc

03.WPF and want default VLC libs
 xZune.Vlc.Wpf.WithLib (will bring xZune.Vlc.WithLib via dependency, which will also bring xZune.Vlc.Lib)

04.WPF and has custom VLC libs
 xZune.Vlc.Wpf (will bring xZune.Vlc via dependency)

So then one just needs to use either xZune.Vlc or xZune.Vlc.Wpf, or xZune.Vlc.WithLib or xZune.Vlc.Wpf.WithLib in their project. That is they just add ONE NuGet package and it brings what is needed. Adding multiple NuGets for the same thing is a bit strange and may be harder to understand and maintain (e.g. one might accidentally upgrade just one package of the two if they have to add two ones manually)

**Comment by birbilis** [comment]
so what I suggest is to keep it as you have it now and also add xZune.Vlc.WithLib and xZune.Vlc.Wpf.WithLib. Those can be EMPTY packages (no extra dlls in them) and just contain dependencies:

1) xZune.Vlc.WithLib would depend on xZune.Vlc and xZune.Vlc.Lib
2) xZune.Vlc.Wpf.WithLib would depend on xZune.Vlc.Wpf and xZune.Vlc.Lib

so like that you help your user and NuGet can take care of upgrading in pair both packages from [1] and [2] if somebody used xZune.Vlc.WithLib or xZune.Vlc.Wpf.WithLib at their project. Also it's much simpler for the user to just add one of those two (For console and for WPF) and have it bring what's needed (WithLib suffix means that it will also bring xZune.Vlc.Lib in via dependency)

**Comment by higankanshi** [comment]
Is it too complex?
I will maintain 5 muget packages...

**Comment by birbilis** [comment]
you have a point there if you don't use myget or something to autopublish to NuGet

**Comment by birbilis** [comment]
then you'd just have to edit the version number of the .nuspec files and commit to GitHub

**Comment by birbilis** [comment]
btw, I have an issue with the new NuGet package xZune.Vlc.Lib

I add it at a library project and I need it to copy the libraries to the folder of the .exe that uses the library. If I right click each dll in the library project (your NuGet adds them to the library project) and change the "Copy to output folder" to "Copy if newer" (you have it to not copy) then when I build my EXE it does copy them fine from the library project

I don't want to add the NuGet package to my EXE project too since then I'd have to upgrade the package at two locations (both at the library project and at the EXE) which is errorprone (might forget one of the two, ending up with the exe using older VLC DLLs)

So, does .nuspec allow you to tell VS to set the option "Copy to output folder" to "Copy if newer" for all those DLL files that xZune.Vlc.Lib package contains?

**Comment by birbilis** [comment]
btw, regarding the .WithLib packages I had suggested, if NuGet allows you to specify them as "requiring latest" of xZune.Vlc.Lib and of xZune.Vlc or xZune.Vlc.Wpf (for xZune.Vlc.WithLib and xZune.Vlc.Wpf.WithLib) respectively, then you only need to make/publish them once, since they're empty (they just have the two dependencies needed to pull-in the latest versions of both the native and the managed code libs). Regarding versioning of that package, I'd use 0.0.0 since it never changes (and if you do minor change to it, a 0.0.1 etc.), so that users don't confuse its version number with the one you use at the other libs

**Comment by higankanshi** [comment]
Ummm...I still think there are too many package will make people confused...

**Comment by birbilis** [comment]
did you check why it doesn't mark those DLLs as "copy if newer" at "copy to output project" property? Maybe you didn't tell NuGet they're native dlls and it thinks they're some content files or something? Even in that case though I'd expect NuGet to have some option to tell it to copy at build the files at the EXE folder via copy-if-newer

**Comment by higankanshi** [comment]
Ummm...I can't find any option with it...

**Comment by birbilis** [comment]
there is some new, but is only for VS2015 I see which is sad - probably if you add it older package manager versions will complain

**Comment by birbilis** [comment]
this is the setting, but I really don't understand if VS2013 or earlier will fail while trying to install such NuGet package or will just ignore the extra info. If it just ignores it and installs ok, then maybe use this feature (have to read about it carefully first though, see url below) for VS2015 Update 1 users sake (maybe they add it to earlier Visual Studio too, not sure, afterall NuGet package manager is a VS extension) and have some note to ones using earlier ones at the description of that package to set the copy to output folder for each file to copy if newer (can select multiple files and set that option to all of them from properties dialog, but have to select files of same type, that is .dll, .jar and .dat files handled separately from the files under the LibVlc subfolder that xZune.Vlc.Lib adds to your project)

copyToOutput	If True the content items will be copied to the build output folder

https://docs.nuget.org/create/nuspec-reference

ContentFiles with Visual Studio 2015 Update 1 and later

In order to provide a better experience and clearer definition of what files should be included in a project, the new contentFiles element has been introduced to the nuspec. These package content files are designed to be immutable, and should not be modified by developers who install the package.

The contentFiles element contains a collection of files elements that define a mask of files and how those files should be references by a project.

Files elements in the nuspec are applied from top to bottom, with the topmost elements taking precedence over lower elements in the collection. These elements apply to entries in the contentFiles folder of the package.
