### ISSUE TITLE
Can I get decoded frame data?

### ISSUE THREAD

**Issue by shinkamui** [higankanshi/xZune.Vlc#58]
I'm working on some sort of cv job, need decoded image directly send to my code for follow up processing. Display is not needed in my case, all I need is efficent data copy. Snapshot maybe not efficent enough. So is there any way to get every frame data?

**Comment by shinkamui** [comment]
solved! thanks!!

**Comment by higankanshi** [comment]
If you only want to get frame data one by one...
You can see `VideoDisplayCallback` and  `VideoLockCallback`...Maybe you can change some code to get this...

If you want to get frame data on background or by time index....
I don't know are there some api of LibVlc to do it...
