### ISSUE TITLE
Stretch for the WPF VlcPlayer element

### ISSUE THREAD

**Issue by Manu1985** [higankanshi/xZune.Vlc#6]
I have another feature request. Is it possible to integrate a stretch to display the video with different stretch options?

https://msdn.microsoft.com/de-de/library/system.windows.media.stretch(v=vs.110).aspx

**Comment by higankanshi** [comment]
Ummm...I See...It's easy to do it.
I'll add it later.
Now I have to handle issue #5 .

**Comment by Manu1985** [comment]
That is no problem.

**Comment by higankanshi** [comment]
Ok,I have added “VlcPlayer.Stretch” and "VlcPlayer.StretchDirection" properties.
They are "DependencyProperty".

You can use it for binding.

**Comment by Manu1985** [comment]
I will try it in the next days and give you a Feedback.

**Comment by Manu1985** [comment]
I have tested in and it is working, but I have one problem. I need the "UniformToFill" for my project.

I think, that "UniformToFill" stretches the image and center it to the middle. I have tested it and the video is not centered in the middle, it is centered at the top of the video.

**Comment by higankanshi** [comment]
I see...Ok...
Now you can set "HorizontalContentAlignment" and "VerticalContentAlignment" to "Center" to get it.

It also useful for "Left" , "Right" , "Bottom" and "Top".

**Comment by Manu1985** [comment]
Thanks. Now it is working perfect.
