### ISSUE TITLE
关于在线视频往回拖拽的问题

### ISSUE THREAD

**Issue by suxiaoyi** [higankanshi/xZune.Vlc#60]
在本地进度条可以任意拖拽，播放在线视频的时候。可以往后拖拽，却不能往前拖拽。即如果我在看第10分钟，我可以拖到10分钟以后的任意位置观看，却不能拖到10分钟以前的位置。视屏会卡掉或者直接从第10分钟继续播放，您知道是怎么回事吗？

**Comment by higankanshi** [comment]
额，没有出现过这种情况，请问一下是用什么协议传输流视频的？HTTP？还是RSTP？或者其他的什么。
另外是能否提供一个测试的流视频链接？用于我之后的测试...

**Comment by suxiaoyi** [comment]
http://site-innermediaplayer.jjsoft.cn//RequestFile/Get/2095765c707e5019a7fa09af8deca3f1,mp4

**Comment by higankanshi** [comment]
嗯，我试过了，确实有这个原因，我测试了一下原生的 VLC 貌似也差不多。
主要原因是往前跳的时候，跳到了没有缓冲的帧上面，然后由于资源所在的 HTTP 服务器貌似不支持相关的协议，例如：渐进式下载 之类的，也有可能是因为资源本身格式的原因，无法重新缓冲之前的数据。

我自己搭建了一个本地的 HTTP 服务器，测试了一个视频（MP4 1920x1080 H.264+AAC），发现无论是使用原生 VLC 或者是 xZune.Vlc 的示例应用，都能完美的跳转视频，这也有可能和带宽有关。

**Comment by suxiaoyi** [comment]
本地搭建rstp服务器，也可以完美的跳转。谢谢。
