### ISSUE TITLE
I can not repeat the application to open the video page

### ISSUE THREAD

**Issue by Jefferson-zh** [higankanshi/xZune.Vlc#65]
The first open can be normal play, the second open “VlcMediaPlayer” is null

code:
vlcPlayer.BeginStop(() =>
            {
                vlcPlayer.LoadMedia("rtmp://127.0.0.1/live/test");
                vlcPlayer.Play();
            });

**Comment by higankanshi** [comment]
Second open？
Stop the media then replay？
Or second navigate to the page which include VlcPlay?
Ummmm....
BTW, Are you using nuget?

**Comment by higankanshi** [comment]
I have update the nuget package.
I think it is fixed in this version.

**Comment by Jefferson-zh** [comment]
my using source code by Version: 20151112

**Comment by Jefferson-zh** [comment]
Thank you very much for your timely solution to my problem.
