### ISSUE TITLE
Stop not working

### ISSUE THREAD

**Issue by kmcginnes** [higankanshi/xZune.Vlc#66]
It looks like you already know about the issue, but I wanted to create this to track the work.

When `Stop()`, `StopAsync()`, or `BeginStop()` are called the app will lock up. This seems to be caused by the events not propagating to the `StopRequest` object. So the state machine never progresses to the next step.

This happens regardless of the state of the media (playing or paused).

Any thoughts on why this is happening?

**Comment by higankanshi** [comment]
Ummmm...Actually I don't know that.
App will be deadlock when you called Stop method group?

**Comment by kmcginnes** [comment]
I figured someone knew something because I saw these comments in `VlcMediaPlayer.cs`

```c#
_onStoped = OnStoped;  //This Event has something wrong.
// ... snip ...
_onStopedHandle = GCHandle.Alloc(_onStoped);  //This Event has something wrong.
```

Maybe this is a side effect of my other change to allow multiple instances of `VlcControl`... ?

I'll try removing one of my VLC instances and see how it reacts.

**Comment by kmcginnes** [comment]
Ok, so it seems to happen with a single player as well.

**Comment by kmcginnes** [comment]
Seems to happen mostly when the player is paused when closing the app.

Also, it might be worth noting that in `VlcPlayer.Dispose()` we call `BeginStop`. This will execute asynchronously and therefore the typical window closing logic will continue before `BeginStop ever gets to calling the callback or fully stoping the media.

We may want to think about using `StopAsync().Wait()` to make sure everything gets cleaned up properly. Of course we'll have to make sure that Stop is working a bit better than it is now... :)

**Comment by higankanshi** [comment]
Ummmm....When you make the main thread blocking, it will case deadlock when you call any media operation(Play, Pause, Stop).

I think our video callbacks have some resource conflict  with those operation.

When you stop the one of VLC instances, will it be deadlock too?

Maybe we have to know more about what libvlc do when we stop the media to solve this issue. 

BTW, `//This Event has something wrong.`, it is written by me. It is invalid now. Don't mind.

**Comment by higankanshi** [comment]
I have changed stop method group, you can try new stop method.
