### ISSUE TITLE
Question: Is it possible to use this with Windows Forms?

### ISSUE THREAD

**Issue by lucasloss** [higankanshi/xZune.Vlc#68]
Hello,
First of all, I know that this project is for WPF. I downloaded it and was able to run it. Unfortunately I need some way to run it on my Windows Form application.
Is it possible to do that? I tried to create a xZune.Vlc.Forms.Sample project using the ElementHost control, but it didn't work.
Is it possible to create a VlcPlayer control for Windows Forms? 
Thanks very much!

**Comment by higankanshi** [comment]
Ummm...If you want to use LibVlc on WinForm.
I recommend you this project [VLC.Dotnet](https://github.com/ZeBobo5/Vlc.DotNet) .

**Comment by lucasloss** [comment]
Thanks.

I'm already using Vlc.DotNet on my project. It works perfectly, and it has everything that I need.
But... there is a bug that I'm not able to solve: setting the volume before playing the audio file doesn't work. Setting the volume only works once the audio file is already playing.
I already created an issue on the project site and on Stackoverflow to see if someone knows how to solve it, but, until now, no answers.
The bug is described here: [Vlc.DotNet Issue] (https://github.com/ZeBobo5/Vlc.DotNet/issues/130)

If you know a little about the Vlc.DotNet, would you mind reading about the bug and maybe suggest an way to fix it? It would really help me! 

Anyway, thanks for the reply. And congratulation on the xZune.Vlc project. It is really nice! :)

**Comment by higankanshi** [comment]
Ummm...I have check some code of Vlc.DotNet, but I can't find any problem.
It is interesting.

BTW, you can create a WinForm control with xZune.Vlc, It is easy to do it.
I'm using Callback in WPF, you can use hwnd on WinForm.

**Comment by higankanshi** [comment]
I have found the problem.
You should use LibVlc 2.2.0(or later).

Vlc.DotNet is using LibVlc 2.1.5

**Comment by lucasloss** [comment]
Really?! Thanks very much! You're awesome!
I'm going to try it right now! I get back here to post the results! =)

**Comment by lucasloss** [comment]
higankanshi,
Thanks for helping on such short notice. You're right. Using the LibVlc 2.2.0 I'm able to set the Volume before playing. 
Unfortunately, it only works on the first time the application is opened. For some reason, setting the volume before playing the audio only works on the first time the application is opened. After stopping the audio, changing the volume, and playing it again, the volume doesn't change.
Here are the steps with results:
 1. Execute the application;
 2. Change the volume at run time before playing an audio file;
 3. Play the audio file;
* RESULT: the audio plays at the specified volume, successfully! =)
 4. Press Stop;
 5. Change the volume again;
 6. Press Play again (at this point, the implementation inside the play method should get the new volume information);
* RESULT: the audio plays again at the same volume it played before. Setting the volume doesn't work anymore.

I'm going to explain this properly at the Vlc.DotNet issue page, and I'm going to put more information and code there.
Thanks very much for helping! It didn't crossed my mind to change the LibVlc.

Please, if you have the time and interest, would you mind testing it again to see if you are able to understand what the problem is? Or do you think it is the correct behavior?

**Comment by lucasloss** [comment]
Regarding creating a WinForm Control with xZune.Vlc.
I would love to do that! 

But, I have to be very honest with you: I don't understand the concepts of Callback and Hwnd. 
So, I don't even know where to start. =(

For now, I'm going to try a little longer to fix the volume problem with the Vlc.DotNet. If I'm not able to do that, I'm going to study your suggestion to see if I would be able to do it.

On the other hand, here's a suggestion: since your xZune.Vlc seems to be very stable, you could create the WinForm Control on your project, and also create a Form Sample. That way you could still say that your project is focused on WPF but, for those who need to add it to a WinForms application, could use the WinForm Control also available on the project. That way you could reach more people.

But again: thanks for helping me! It really changed my day. =)

**Comment by lucasloss** [comment]
@higankanshi,

You may add a **function request** label on this issue, since on the earlier comment I suggested that you could create the WinForm control and add it to the project.

Also, I have already posted my comments with code samples on the [Vlc.DotNet issue page] (https://github.com/ZeBobo5/Vlc.DotNet/issues/130), regarding the Volume problem. So, regarding the volume problem on the project, I think we should continue the discussion there, since that is not related to your project.

Thanks!

**Comment by higankanshi** [comment]
Ummmm...I have checked this.
I find this problem in xZune.Vlc too.

I think it is a LibVlc issue.
When player's state is Stopped if you set volume it will return -1 and volume will be -1.
It is LibVlc's document:
```C
LIBVLC_API int libvlc_audio_set_volume  ( libvlc_media_player_t *  p_mi,  
                                          int  i_volume)   
// Set current software audio volume. 

// Parameters
// p_mi media player  
// i_volume the volume in percents (0 = mute, 100 = 0dB)  

// Returns
// 0 if the volume was set, -1 if it was out of range 
```

Maybe I can do some cache in xZune.Vlc to fix this.
If you want fix it in Vlc.DotNet, I think you should cache volume in your app too.
 1. Cache your setting volume.
 2. When you change volume cache it and set it.
 3. When player's state changed to Playing, set it again.

Ummmmm...I don't think xZune.Vlc is very stable, actually I don't think LibVlc is stable, LibVlc has many knows issue. I'm still maintaining xZune.Vlc, but I really want to warp a ffmpeg library by .NET.

If you want to create a WinForm Control with xZune.Vlc.
I think I can help you.

LibVlc has provide many ways to display video.
We can use Hwnd (Windows API window handle) and VideoCallbacks.

Winform is based GDI, so each control has a Hwnd, if you set control's Hwnd to "xZune.Vlc.VlcMediaPlayer.Hwnd" LibVlc will draw video on this control. So do Vlc.DorNet.
If you use this way, you will be easy to create a control, LibVlc will do most of work what you need. like: inactive, display, lock buffer, unlock buffer and set decode format.

WPF is based DriectX, so every controls have no Hwnd, except for Window control.
So I use VideoCallback to display video, I alloc some memory, make it be shared memory. LibVlc will decode video's frames to those memory, I will get every frames pixels. then I build a BitmapImage by those pixels, show it by image control.
If you use this way, you will do all work by your self, but you can customize a lot of things.

**Comment by lucasloss** [comment]
My observations/comment below:
 1. What I don't understand is: if it is a LibVlc issue, how come on the VLC Player (vlc.exe) the same problem doesn't happen?
 2. I don't understand what do you mean by Cache. What does it mean to *cache your setting volume*? 
 3. I have already tried to change the volume when player's state changed to Playing. That works, but the first milliseconds of the audio (maybe half a second... or a full second) are played in the previous volume and then the volume changes. So, if the volume was 100% and I changed it to 40%, the first half-second of the audio is going to play at 100%, and then it will lower to 40%. It is really annoying.

**Comment by lucasloss** [comment]
I'm starting to think that I wasting time on a problem because of my initial idea to use the VLC library.
I've made this decision because my application needs to run most of the audio file types available. So, based on that, and based on the fact that VLC comes with all plugins necessary to do that job, it seemed obvious that using VLC embedded on my application was the right option. Apparently I was wrong.

The other option would be to write code for every audio type I want my application to run. But that would be a lot of work that I'm unwilling to do.
I see only three options:
 1. Use the VlcLib as it is - and ignore the Volume problem and other problems I might get on the way;
 2. Make my application read only one or two types of audio files (lets say MP3 and WAV);
 3. Make a generic player (like most of the players around), that depends on the plugins installed on the user's machine (like the way Windows Media Player works);

Not sure what I'm going to do. 

But thanks for all the time and help on this matter! =)
It is really nice to find someone to help us and discuss the problem. =)

**Comment by higankanshi** [comment]
Ummm.... I'm not good at English...

VLC is not all based on LibVlc, VLC can use some API which LibVlc don't have.

Ummm...StateChanged is not immediate. 
I'll try AudioCallbacks...If I have any progress I'll post it.

**Comment by higankanshi** [comment]
News here, I cache volume value when media stopped.
Then I set really volume in video callbacks.
You can see my commit.https://github.com/higankanshi/xZune.Vlc/commit/fbfcd442bd44638847b7fdcf6c0c541b73913c3c

**Comment by lucasloss** [comment]
@higankanshi 
I downloaded and tested. Works fine for video. But for audio (for example, MP3), the problem is still there.
I haven't had the time to see the code. I going to look at that later.
Any change to make it work for audio too?

**Comment by higankanshi** [comment]
I try to use AudioCallback, but I don't find a simple way to play PCM sample data.
