### ISSUE TITLE
Switch audio channel/track

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#7]
DVD movies and MKV video files can have multiple audio tracks (for example in different languages) and VLC supports that. It would be nice if we had a list of all available sound tracks with their title/description and were able to switch between them.

**Comment by higankanshi** [comment]
Ummm...I see, I will add it later.It's easy to do it.

**Comment by higankanshi** [comment]
I have added “AudioTrackCount” “AudioTrack” and “AudioTrackDescription”.
Those Properties can help you control the AudioTrack
