### ISSUE TITLE
I can build it with x64

### ISSUE THREAD

**Issue by seekerquoc** [higankanshi/xZune.Vlc#70]
Hi,

when i build xZune with x64, it show me this error about badimageException.

Thanks

**Comment by higankanshi** [comment]
You need use LibVlc x64.
I don't provide it , you should get it by yourself.
http://www.videolan.org/

**Comment by seekerquoc** [comment]
i buit LibVlc x64 but when build xZune.VLc give me error

A first chance exception of type 'System.Exception' occurred in xZune.Vlc.dll
A first chance exception of type 'System.Xaml.XamlObjectWriterException' occurred in System.Xaml.dll

can you help me?

**Comment by higankanshi** [comment]
I need more information....
