### ISSUE TITLE
support VLC64 

### ISSUE THREAD

**Issue by soapgu** [higankanshi/xZune.Vlc#71]
Hi,I can play vlc with x86 vlc。
the program will crach when I set libVlcPath with x64.

**Comment by higankanshi** [comment]
You need run it on x64 mode, not AnyCPU and x86.

**Comment by soapgu** [comment]
Thank you.I find I use wrong reference.I need use the dll in x64 directory

**Comment by seekerquoc** [comment]
can you give me libVlc 64, i downloaded it from vlc, but when build not working"

this is error:

http://screencloud.net/v/9SSx
