### ISSUE TITLE
vlc 64

### ISSUE THREAD

**Issue by seekerquoc** [higankanshi/xZune.Vlc#72]
can you give me libVlc 64, i downloaded it from vlc, but when build not working"

this is error:

http://screencloud.net/v/9SSx

**Comment by seekerquoc** [comment]
http://screencloud.net/v/8J00, i run with 4 cameras(RTSP)

**Comment by higankanshi** [comment]
In your first screenshot, I don't found any build error...

About performance issue, I can't do anything. You open 4 VLC, you will get 100% too.

**Comment by seekerquoc** [comment]
i just change debug mode to x64 and change libvlc and it show this error when build

**Comment by higankanshi** [comment]
What error？

**Comment by seekerquoc** [comment]
http://screencloud.net/v/9SSx

This is error when i change mode x64

**Comment by seekerquoc** [comment]
can you give me libvlc x64, i used to libvlc x64 from vlc.org but its not working

**Comment by higankanshi** [comment]
I see no error in your screenshot, if you mean "Design View is unavailable for x64 and ARM target platforms".
 it is not a error, because XAML Designer is only work on x86 platforms, actually VisualStudio is only have x86 version too.
So, you can't use XAML Designer on x64 mode, it can't load x64 dll.

You can Design your app on x86, and debug on x64.

**Comment by seekerquoc** [comment]
Ok, but x64 better than x86 for perfomance, right?
because i want to fix issue with cpu vlc

Vlc player just 5-10% cpu

but your project it used to 25-30%

**Comment by higankanshi** [comment]
Ummm, I have no idea to fix this performance issue, I have used some diagnosis tools for it, but everything look good.

Maybe you can try other project [Vlc.DotNet](https://github.com/ZeBobo5/Vlc.DotNet).

**Comment by seekerquoc** [comment]
yeah, latest version is good, just took 10% cpu. you just disabled show log and it just took 10% cpu

thanks
