### ISSUE TITLE
 Memory stream & multi audio output devices

### ISSUE THREAD

**Issue by anhlunnhaque** [higankanshi/xZune.Vlc#73]
Hi higankanshi,

Thank you for pointing me to this project. I think this have some of the features/options that I've been looking for my WPF project. 
Looking at the code. I have two questions and was wondering if this supports it.

1. Support playing from memory stream?

2. Support multiple output audio devices.
Ex: I have 2 audio cards in my desktop. My app have two player instances (Player1 play the movie SpiderMan. Player2 play the movie SuperMan).
How do attach Player1 to audio card 1 and Player 2 to audio card 2?

Update:
3. Normalize audio ?

Thanks.

**Comment by higankanshi** [comment]
> 1.Support playing from memory stream?

Sorry, LibVlc don't support it, I can't do it.  
> 2.Support multiple output audio devices.

I add audio dvice APIs in last commit, you can have a try, I don't test it, I don't know id it work fine.
See :[LibVLC audio controls](http://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__audio.html)
> 3.Normalize audio ? 

What's this mean?

**Comment by anhlunnhaque** [comment]
Hi,
Thanks for the quick reply.

Normalize audio:
In VLC go to Tools>Preferences>Audio>Normalize volume check box (under Effects).
For example. I have a music video where the audio is low/soft. When I check the 'Normalize volume' checkbox. The audio is louder during playback. A.K.A 'Audio Gain'

Is there a reason why in the VlcPlayer class have the same method 'VlcMediaPlayerStateChanged' for the below EventHandler?
                VlcMediaPlayer.Playing += VlcMediaPlayerStateChanged;
                VlcMediaPlayer.Paused += VlcMediaPlayerStateChanged;
                VlcMediaPlayer.Stoped += VlcMediaPlayerStateChanged;
                VlcMediaPlayer.Opening += VlcMediaPlayerStateChanged;
                VlcMediaPlayer.Buffering += VlcMediaPlayerStateChanged;
                VlcMediaPlayer.EndReached += VlcMediaPlayerStateChanged;

I will try out the 'audio device APIs'. Do I have to use VLC 3.0? My current VLC version is 2.2.1

Thanks.

**Comment by higankanshi** [comment]
Ummm, I see, I don't find any api about normalize volume in libvlc.

Yeah, those event all are state changed, isn't it?
I think use 6 event in app isn't good, so I merge those in a event.


VlcMediaPlayer is lowest layer API, it provide all any API we have, VlcPlayer is easiest API, I think you can use it by easy way is VlcPlayer's job.

VLC 3.0.0 isn't work now, it is still in progress. Only one api need 3.0.0(GetVideoDevice), if you don't need it 2.2.1 is best version.

**Comment by anhlunnhaque** [comment]
Perfect. Thank you for the help. I am a newbie at this. Please excuse my stupidity. I'll start my WPF app today. Will come back for help.

Thanks.

**Comment by higankanshi** [comment]
I have try it. There some problem on create AudioOutput or AudioDevice sturct, but I have fix it.
It work fine now, on my two audio device.

```CSharp
var devices = Player.EnumAudioDeviceList();  // Get all device, the first one aways is default.
var outputs = Player.GetAudioOutputList();   // Get output list, you can find DSound output or Wave output on this.
Player.SetAudioDevice(null, devices[2]);     // Set audio device, if the first one is null, it will not change the output.
```
