### ISSUE TITLE
how to run vlm.conf

### ISSUE THREAD

**Issue by jaythree03** [higankanshi/xZune.Vlc#74]
Is there a way to run a vlm.conf?

**Comment by higankanshi** [comment]
Ummm, we have some wrapper of LibVlc  VLM, see [LibVlc.VLM.cs](https://github.com/higankanshi/xZune.Vlc/blob/master/xZune.Vlc/Interop/LibVlc.VLM.cs).
But I don't know how to wrap a class for it, in fact I don't know what is VLM and how it work with Vlc player.

**Comment by jaythree03** [comment]
VLM is for playing multiple streams at the same time. I need to run 5 streams simultaneously. have you tried doing it?

**Comment by higankanshi** [comment]
Run multiple streams and display those? Or need not display?

How it work with Vlc player?
If you have a sample to use LibVlc VLM, I think I can do it.

**Comment by jaythree03** [comment]
I could run multiple streams at the same time but the problem is I need to record all those streams in parallel. example: 
https://wiki.videolan.org/Documentation:Streaming_HowTo/VLM/

**Comment by jaythree03** [comment]
for the VLC player, you can import a  VLM.conf.

here's a sample VLM.conf:

# VLC media player VLM command batch
# http://www.videolan.org/vlc/

new video1 broadcast enabled
setup video1 input "C:\Users\Arjay\Desktop\a.mp4"
setup video1 output #file{dst=C:\Users\Arjay\Desktop\test.mp4}
setup video1 option network-caching=1000
new video2 broadcast enabled
setup video2 input "C:\Users\Arjay\Desktop\a.mp4"
setup video2 output #file{dst=C:\Users\Arjay\Desktop\test2.mp4}
setup video2 option network-caching=1000

control video1 play
control video2 play

**Comment by higankanshi** [comment]
Ummmm...I have add some Vlm APIs in Vlc class.
You can try this.
```CSharp
var sout = "#transcode{vcodec=h264,fps=25,venc=x264{preset=ultrafast,profile=main,tune=zerolatency},vb=512,scale=0.5,acodec=mpa,aenc=ffmpeg,ab=64,channels=2}:standard{access=udp,mux=ts,dst=233.233.233.233:6666}";

Player.VlcMediaPlayer.VlcInstance.VlmAddBroadcast("Test", "screen://", sout, 0, null,1,0);
Player.VlcMediaPlayer.VlcInstance.VlmPlay("Test");

Player.VlcMediaPlayer.VlcInstance.VlmStop("Test");
Player.VlcMediaPlayer.VlcInstance.VlmRelease();
```

I think vlm.conf is using by Vlc options, like this:
```
vlc -I telnet --vlm-conf vlm.conf
```
You can set Vlc options on VlcSettings, like this:
```CSharp
//Set the path and options of LibVlc
[assembly: VlcSettings(@"..\..\..\LibVlc", "-I", "telnet ", "--vlm-conf ", "vlm.conf" )]
```

**Comment by jaythree03** [comment]
Thank you! I'll try it out.

**Comment by jaythree03** [comment]
Additional information: Can't find function "libvlc_vlm_add_output" in dll.

I'm encountering this error. What version of should I use to test this?

**Comment by higankanshi** [comment]
Ummm, this is a typo issue lol, it will be libvlc_vlm_add_input, I will fix it later.

**Comment by higankanshi** [comment]
Ok, it ok now.

**Comment by higankanshi** [comment]
If those VLM APIs work fine, maybe I will change it to more easy to use.
You can help me test it.

**Comment by jaythree03** [comment]
![image](https://cloud.githubusercontent.com/assets/34328/13031798/d56fee08-d313-11e5-8501-490493293a25.png)

now I'm having this issue during run-time. 
Do you have skype or wechat so we could talk directly? Thanks!

**Comment by higankanshi** [comment]
Ummm, How do you use it? You call it by yourself or by VlcPlayer?
I'm not good at English, talk maybe have some problems.

**Comment by jaythree03** [comment]
We could chat in skype or wechat. 

[assembly: VlcSettings(@"..\..\..\LibVlc", "-I", "telnet ", "--vlm-conf ", "vlm.conf" )]

I include this to the assembly. then put this in the play button:

var sout = "#transcode{vcodec=h264,fps=25,venc=x264{preset=ultrafast,profile=main,tune=zerolatency},vb=512,scale=0.5,acodec=mpa,aenc=ffmpeg,ab=64,channels=2}:standard{access=udp,mux=ts,dst=233.233.233.233:6666}";

Player.VlcMediaPlayer.VlcInstance.VlmAddBroadcast("Test", "screen://", sout, 0, null,1,0);
Player.VlcMediaPlayer.VlcInstance.VlmPlay("Test");

Player.VlcMediaPlayer.VlcInstance.VlmStop("Test");
Player.VlcMediaPlayer.VlcInstance.VlmRelease();

**Comment by jaythree03** [comment]
[assembly: VlcSettings(@"..\..\..\LibVlc", "-I", "telnet ", "--vlm-conf ", "vlm.vlm")]

I think there's a problem with this line. An exception of type 'System.Exception' occurred in xZune.Vlc.dll but was not handled in user code

**Comment by higankanshi** [comment]
Did you have added vlm.conf file to run dir?

**Comment by jaythree03** [comment]
yes. I include it in the debug folder. where should I put it?

![image](https://cloud.githubusercontent.com/assets/34328/13031876/b5f2c628-d317-11e5-86c3-93fdf5fcaa2f.png)

**Comment by higankanshi** [comment]
I see you set the LibVlc path to "......\LibVlc", maybe it will be "..\..\..\LibVlc".

**Comment by higankanshi** [comment]
I don't know why Vlc pointer is NULL, something error with Vlc initialize.
You can try don't set the vlm.conf, if it work fine with no vlm.conf maybe something error in it.

**Comment by jaythree03** [comment]
it's spacing issue haha. 
you put spaces in between. now it's working. I'll try it now in the CCTV. I'll update you again.

**Comment by jaythree03** [comment]
now my problem is there's a bug in the VLCLIB. Actually, this is also my problem with vlc.dotnet. is there a way we could use lower versions of VLC? like 2.1.6?

**Comment by jaythree03** [comment]
or 2.2.1

**Comment by jaythree03** [comment]
![image](https://cloud.githubusercontent.com/assets/34328/13032082/69d03538-d320-11e5-9688-b22c853913a9.png)



when I use a lib of vlc, I'm encountering this error.

**Comment by jaythree03** [comment]
The bug is when I record a stream, it will stop the recording in the 2 seconds mark.

**Comment by higankanshi** [comment]
Ummm, some typo case this exception. I have fixed it.
LibVlc version string must like: "2.2.0-xZune Weatherwax", "2.2.0-xZune".

If you get new type of version string, you can tell me.

**Comment by jaythree03** [comment]
May I know your wechat or any chatting platform so I could message you directly? I think I need help modifying the VLCLib so this implementation will become successful.

**Comment by jaythree03** [comment]
MayI use 2.1.5 VLC? that's the only version working right now. How?

**Comment by higankanshi** [comment]
You can have a try.
