### ISSUE TITLE
Over 50% CPU usage for 1 insance by default

### ISSUE THREAD

**Issue by anhlunnhaque** [higankanshi/xZune.Vlc#76]
Hi,

I just pulled the latest code 5 minutes ago. The 'xZune.Vlc.Wpf.Sample - .Net 4.5' project took ~53% while playing 1 music video. VLC cpu usage is ~23%. Is this normal? I read in this ( #72  ) saying to disable log. I don't think logging is enable as I don't see any logging window while playing.

Any idea to improve this? Maybe GPU

Update:
I've read old post here and can't find any help with the latest build.

Thanks.
![xzuneperf](https://cloud.githubusercontent.com/assets/16323974/13053586/e206cdbe-d3ca-11e5-954e-e54f45929988.PNG)

**Comment by higankanshi** [comment]
Have you try release mode? and more times to try?
I think VLC 25%, xZune.Vlc 30% is normal.

**Comment by anhlunnhaque** [comment]
Yes. Release mode is around 30%.
Thanks.
