### ISSUE TITLE
Play YouTube Video

### ISSUE THREAD

**Issue by ORRNY66** [higankanshi/xZune.Vlc#77]
Hello,
What method can play a YouTube video by xZune.Vlc. I tried different ways but nothing worked. Thanks a lot

**Comment by higankanshi** [comment]
I don't known about how to play a YouTube video, but I think if you can get the url of the video, you can use xZune.Vlc to play it.

**Comment by shaunthasheep** [comment]
You can use flagbug/YoutubeExtractor to get the video URLs. Most of the HD videos I don't think you can stream easily unless its without the audio. I'm looking to switch away from the MediaPlayer and I just found this project. One of the things I need to do is stream YouTube videos so if I get it to work I'll let you know.

**Comment by shaunthasheep** [comment]
I was able to just put the url of the youtube video into the sample and hit load and it streamed fine.

**Comment by ORRNY66** [comment]
Hi,
to acquire YouTube video URL using Google.Api.YouTube.v3.


YouTubeService youtube = new YouTubeService(new BaseClientService.Initializer() {
    ApplicationName = "{yourAppName}",
    ApiKey = "{yourApiKey}",
});
SearchResource.ListRequest listRequest = youtube.Search.List("snippet");
listRequest.Q = "Batman v Superman Dawn of Justice Official Final Trailer (2016)";
listRequest.MaxResults = 5;
listRequest.Type = "video";
SearchListResponse resp = listRequest.Execute();
foreach (SearchResult result in resp.Items.Take(1)){
            IdVideoYouTube  = result.Id.VideoId;
}

I need to just play video through xZune.Vlc, but it does not work

Player.LoadMedia(new Uri("https://www.youtube.com/watch?v=" + IdVideoYouTube));
Player.Play();

Thanks a lot

**Comment by higankanshi** [comment]
I think you should get the real video address, not a web address.

**Comment by shaunthasheep** [comment]
You can use the project flagbug/YoutubeExtractor to get the direct url to the youtube video.
`string link = "insert youtube link";
/*
 * Get the available video formats.
 * We'll work with them in the video and audio download examples.
 */
IEnumerable<VideoInfo> videoInfos = DownloadUrlResolver.GetDownloadUrls(link);
VideoInfo video = videoInfos
    .First(info => info.VideoType == VideoType.Mp4 && info.Resolution == 360);

//then tell vlc to play video.DownloadUrl`

**Comment by ORRNY66** [comment]
Thanks so much already it works
