### ISSUE TITLE
VersionStringParseException for Vlc ver. 2.2.1

### ISSUE THREAD

**Issue by anhlunnhaque** [higankanshi/xZune.Vlc#78]
Hi,

I think there's a bug in when I am trying to create an instance of the player dynamically/code-behind (not in xaml). Looks like it's trying to look for 2.2.0. I have Vlc ver. 2.2.1.

Thanks.
![xzunevlcver](https://cloud.githubusercontent.com/assets/16323974/13064609/19d04640-d41a-11e5-9930-3f334feeb4a8.PNG)

**Comment by higankanshi** [comment]
Ummm, I think the version string is `<ver>-<devString> <codeName>` before.

Now I add more parser for new version string format.

**Comment by higankanshi** [comment]
Have you try the new version?
I think it work fine now.
