### ISSUE TITLE
Subtitle support

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#8]
I may be missing something but I don't see any function or property for setting subtitle and changing its settings. We need support for embedded subtitles (Providing a list of all subtitles available and the ability to select the desired one. This is specially useful for DVD/Blu-ray Movies), external subtitle (From file) and something like `SubtitleOptions` to set seed, encoding, font, size, position, etc.

**Comment by higankanshi** [comment]
Ummm...Actually I I canceled the subtitles of LibVlc, because Chinese Font has some problem in LibVlc.
I want to display subtitles by myself.

You can use the subtitles of LibVlc by some options.

xZune.Vlc/Vlc.cs #Line:184 
delete the "--no-sub-autodetect-file"

**Comment by sepehr1014** [comment]
Have you tried setting the encoding to utf-8 and using a proper font in LibVlc? VLC Media Player renders Korean subtitles correctly (I don't have Chinese to test). Playing with the encoding and font may help! And the encoding of the subtitle file should also be checked ...
Also check out: https://forum.videolan.org/viewtopic.php?t=80401

**Comment by sepehr1014** [comment]
@higankanshi  Could you fix the issue with Chinese subtitle using the proper font and encoding?

**Comment by higankanshi** [comment]
Ummm...I will test in this weekend.

**Comment by sepehr1014** [comment]
Any updates on this matter? Is this feature going to be implemented any time soon?

**Comment by bbougot** [comment]
:+1:

**Comment by higankanshi** [comment]
Ummm...I don't know how to set font for subtitle with LibVlc. If you want to do it maybe you should use options.

**Comment by bbougot** [comment]
Settings subtitles using Vlc options do not seem to work for me.  
I set options with : Player.AddOption("--sub-file = " + vm.Movie.SelectedSubtitle.FilePath); 
before loading media (I have also deleted --no-sub-autodetect-file), but nothing appear on screen

**Comment by sepehr1014** [comment]
If subtitle fonts can be set via the options, it may be good enough.
But this library does not currently support subtitles at all. It needs "Toggle Subtitles", "Load Subtitle File", "Choose from Available Subtitles (In DVDs specially)", etc.

**Comment by birbilis** [comment]
have you tried remove the spaces around the equal sign? I needed to use --rtsp-tcp parameter and it was failing because there was a space char after tcp in that string if I remember well (or maybe it was before --, but I think it was at the end of the option string). I was passing those options to the constructor as a string array. It must be a bug I think, not sure if it is at the xZune.Vlc part or in Vlc itself

**Comment by birbilis** [comment]
btw, easiest way to convert to UTF-8 is (SHIFT)+Right click a text file and select Open With> Notepad and then do File/Save As... there and at the bottom use the dropdown to select UTF-8 for the encoding. It also has the nice feature at that dialog to autoselect the current encoding so if it already says UTF-8 there, the file doesn't need conversion

**Comment by birbilis** [comment]
btw, if you want to parse .srt files and display subtitles yourself (say outside VLC area or at a WPF overlay), try getting my CaptionsLib project from the sources of the ClipFlair project at http://ClipFlair.codeplex.com (an older version of that code that didn't use Silverlight Media Framework's CaptionElement for "data storage" is at http://LvS.codeplex.com, however the newer one has also fixed some parsing issues). 

It's quite easy to decouple the CaptionsLib code from SMF's CaptionElement by making your own same named class to keep the caption time and text. Note that caption formatting isn't supported and it has been used with UTF-8 files exclusively. 

Can try that code online at http://studio.clipflair.net if you use a browser that supports Silverlight (e.g. Firefox, IE11, Opera, or Chrome with the IE Tab extension installed). Just make a new activity there and drag-drop an .srt file in it (that will spawn a Captions component and open the .srt in it). Or open an existing activity that has a Captions component (say from the Activity Gallery at http://gallery.clipflair.net) and drag-drop an .srt file on the captions component to replace its captions list
