### ISSUE TITLE
Open a file and freezing

### ISSUE THREAD

**Issue by ORRNY66** [higankanshi/xZune.Vlc#80]
Hello,
I have a problem with opening the files. When I try to open a file

            var openfiles = new OpenFileDialog();
            if (openfiles.ShowDialog() == true)
            {
                Player.BeginStop(() =>
                {
                    Player.LoadMedia(openfiles.FileName);
                    Player.Play();
                });
            }

So after a few opening an application freezes or appears in this message.

"Additional information: Attempted to read or write protected memory. This is an indication Often That other memory is corrupt."  http://i.imgur.com/u6Cwbbq.png

Thanks so much for any advice.
The application is created in WPF and use .NET4.5

**Comment by higankanshi** [comment]
Which version of xZune.Vlc you have used?
It like access a wild pointer, have you check pointer of VlcMediaPlayer and VlcMedia?

I have try your code on Sample APP, it work fine.

**Comment by ORRNY66** [comment]
I use the current version (16.2.19)

**Comment by ORRNY66** [comment]
I tried almost all possible ways of opening the file, but the application either freezes or error message appears

**Comment by shaunthasheep** [comment]
Did you add this line to the AssemblyInfo.cs file?
`[assembly: VlcSettings(@"LibVlc", "-I", "--dummy-quiet", "--ignore-config", "--no-video-title", "--no-sub-autodetect-file")]`
and then the LibVlc folder with your exe

**Comment by ORRNY66** [comment]
Yes in AssemblyInfo I have been sold. So when I attach source code
https://drive.google.com/file/d/0B_9vA9RdHJmcWks1SE1HQUh3cEk/view?usp=sharing

**Comment by higankanshi** [comment]
It work fine on my pc, I don't know what's your problem.

![Work fine](http://blog.higan.me/content/images/2016/02/QQ--20160219130843.png)

**Comment by ORRNY66** [comment]
I tested it on other computers with various video and audio files and still the same error appeared either frozen or application message appeared that there was an attempt to read or write protected memory. Rocha but I was looking around and I solved the problem. Place this code to open the file

var openfiles = new OpenFileDialog();
            if (openfiles.ShowDialog() == true)
            {
                Player.BeginStop(() =>
                {
                    Player.LoadMedia(openfiles.FileName);
                    Player.Play();
                });
            }

I used this code

 var openfiles = new OpenFileDialog();
            if (openfiles.ShowDialog() == true)
            {
                System.Threading.Tasks.Task.Run(() =>
                {
                    System.Threading.Thread.Sleep(200);
                    Player.Stop();
                    Player.VlcMediaPlayer.Media = null;
                    Player.LoadMedia(openfiles.FileName);
                    Player.Play();      
                });
            }

and now it works well, although sometimes the application is frozen but it works better than before.
I have no idea which was probably a mistake.

**Comment by higankanshi** [comment]
ummm, maybe I found the problem, you are playing a video, then you load a new media, you need stop, but stop is async, media is playing when you call stop, position property will be changed, because position property have `INotifyPropertyChanged`, so it will get new position, but you are stopping this media, it will case deadlock.

I have fix it, you can try new code.

**Comment by mshumilov** [comment]
I had the same issue, and with new fix Stop is working just fine, much more better than before.
Thanks for the fast fix!

**Comment by mshumilov** [comment]
sorry, but still have the same issue

**Comment by higankanshi** [comment]
I need more information for this exception, like: call stack.

**Comment by mshumilov** [comment]
Here is the code:
```
    VideoControl.BeginStop(() =>
                {
                    VideoControl.LoadMedia(itemToPlay.FileFullPath);
                    VideoControl.Play();
                });
```

AccessViolationException on LoadMedia.
Stack:
```
   in xZune.Vlc.VlcMediaPlayer.set_Media(VlcMedia value)
   in xZune.Vlc.Wpf.VlcPlayer.LoadMedia(Uri uri)
   in xZune.Vlc.Wpf.VlcPlayer.LoadMedia(String path)
   in Spotnet.Downloader.Controls.Player.PlayerControl.<>c__DisplayClass31_0.<Play>b__1() 
```

**Comment by higankanshi** [comment]
I have tried to fix it again, you can try the new code, if it work fine, I will update the Nuget Packages.

**Comment by mshumilov** [comment]
it's rarely happens, after many times of video switching, but I've got the same (with the same stack) with the last version.

**Comment by higankanshi** [comment]
Ummm, I have no idea with it, if you can provide your source code, maybe I can get the problem.

**Comment by mshumilov** [comment]
I'll try to create the code, but I've not seen it last week.. strange. For the moment I think you can close it. I let you know if I be able to repeat
