### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by Steinerline** [higankanshi/xZune.Vlc#82]
In VLC player i can activate dxva2 hardware acceleration to reduce CPU load by about 80%.
is that also possible in xZune?

i already tried passing  "--avcodec-hw=dxva2" and   "--avcodec-hw=any" with VLCPlayer.Initialize(), but that didn't work.

**Comment by higankanshi** [comment]
ummm, have you initialize player before?
VlcPlayer will auto initialize when you use it in xaml.
Maybe you can try add your options with VlcSettings, like this:
`
[assembly: VlcSettings(@"..\..\..\LibVlc", "-I", "dummy", "--ignore-config", "--no-video-title","--avcodec-hw=dxva2" )]
`
See the [Quick Start](https://github.com/higankanshi/xZune.Vlc#quick-start) to get more information.

**Comment by Steinerline** [comment]
First of all, thank you for the answer. 
I tried your advice, but it did not work unfortunately. 
I found information that maybe this parameter is supposed to be passed with libvlc_media_add_option _instead of libvlc_new. 
I can only assume that means using this: VLCPlayer.AddOption("--avcodec-hw=dxva2"). 
I am not sure if i need to have a video loaded for this, so i tried it before and after loading a video and it did not work both times. 
if i start VLC player from the command line like this it works: 

vlc.exe --avcodec-hw=dxva2 "Video_Path"

although i dont know what exactly vlc player passes to libvlc. Can you tell me how i have to use AddOption for it to work? 
Thanks again.

**Comment by higankanshi** [comment]
Maybe you can try `LoadMediaWithOptions` method.

**Comment by Steinerline** [comment]
Okay that worked, thank you. 
for future reference: if you want to use hardware acceleration via dxva2, the parameter is ":avcodec-hw=dxva2", NOT "--avcodec-hw=dxva2". for some reason it has to have the  ":". the whole command then is:
VLCPlayer.LoadMediaWithOptions( _VIDEOPATH, new String[] { ":avcodec-hw=dxva2" });

This reduces CPU from 50 to under 20% on my machine.
