### ISSUE TITLE
Get VideoSource from VlcControl

### ISSUE THREAD

**Issue by anhlunnhaque** [higankanshi/xZune.Vlc#84]
Hello,

I am having trouble showing the VideoSource in a separate Window when I create the VlcPlayer in code not xaml. I am trying to use 1 player to play 1 file but show the same Video on multiple UserControls/Windows. It play a file wiht no problem because I can hear the audio but no video showing.

-- Player class --
`public class TestPlayer
{
	VlcPlayer _player = new VlcPlayer {LibVlcPath = VlcX86Lib};
	
	public static TestPlayer Instance
  {
      get { return _player ?? (_player = new TestPlayer()); }
  }
	
	public ImageSource VideoImageSource
	{
	    get
	    {
	        return _player.VideoSource;
	    }
	}
}`

-- Video UserControl --
`<Grid x:Name="VideoGrid" >
    <Grid.Background >
        <VisualBrush Stretch="Uniform">
            <VisualBrush.Visual>
                <Image Source="{Binding VideoSequence}" />
            </VisualBrush.Visual>
        </VisualBrush >
    </Grid.Background>
</Grid>`

-- ViewModel --
`public class VideoViewViewModel : ViewModelBase
{   
    public ImageSource VideoSequence
    {
        get
        {            
            return TestPlayer.Instance.VideoImageSource;
        }
    }
}`

**Comment by higankanshi** [comment]
Ummmm, `VideoSource` will be changed every new media.
Maybe I can create a new Event, you can use it to update your VM.

**Comment by anhlunnhaque** [comment]
Yes. That would be great. Hopefully soon. I'll check for update everyday :)

**Comment by higankanshi** [comment]
Ummm, I have done it.

If it work fine, I will update the Nuget Packages.

**Comment by anhlunnhaque** [comment]
Wow..that was fast. Thank you so much. I'll try it out.

**Comment by anhlunnhaque** [comment]
I got the latest build.
Hmm..Do you have an example? I am not able to see the video in a separate window that is binding to a UserControl.
Maybe it have something to do with what you said from above "VideoSource will be changed every new media."?
I am binding a VideoView.xaml to a VideoWindow.xaml BEFORE I play any file. I do see that the _player.VideoSource is null when I start my app.
So maybe because _player.VideoSource is null and I am binding a null in the VideoView.xaml and VideoWindow.xaml.
Hence, the _player.VideoSource will always be null and not show any video when I actuall play a file after my app started?

Thanks.

**Comment by higankanshi** [comment]
Do you provide any property changed notice?
It is every important for binding.

BTW, we recommend you use VlcPlayer control, because there have some problem to get DAR and SAR with LibVlc, see #32 to get more information.

**Comment by anhlunnhaque** [comment]
I am able to get the video onto a different window with code. Thanks for the help.
