### ISSUE TITLE
LibVlc x64

### ISSUE THREAD

**Issue by Divaite** [higankanshi/xZune.Vlc#85]
Hello.

First of all, thanks for native WPF control for VLC, that's really what we extremly need right now and it's really helpful.
But I have a question, you provide both x86 and x64 xZune.Vlc and xZune.Vlc.Wpf libraries, but only x86 LibVlc for that. Unfortunatelly we cannot use "Prefer 32bits" option in our project. Is it possible to get LibVlc x64 somewhere? If not, is it hard for you to make it?

Do you collecting change and improvement requests for the next releases?

Thanks in advance.

**Comment by higankanshi** [comment]
You can using libvlc x64 form VideoLan.
But if you want to use some extension function for xZune, maybe you should compile it by yourself.

See this wiki to get more information:
[Compile VLC for xZune.Vlc](https://github.com/higankanshi/xZune.Vlc/wiki/Compile-VLC-for-xZune.Vlc)

**Comment by Divaite** [comment]
Thanks for the response.
I downloaded video lan from here [vlc x64](http://download.videolan.org/pub/videolan/vlc/2.2.2/win64/), extracted all dlls and copied them to necessary folder.
At the application start it says: `Can't create a Vlc instence, check your Vlc options.` VlcSettings in AssemblyInfo are added, x86 build works in the same environment.
What am I doing wrong? Btw checked  [vlc 2.2.0 x86](http://download.videolan.org/pub/videolan/vlc/2.2.0/win32/) dlls with yours and libvlc.dll and libvlccore.dll are different. Did I download libvlc from wrong location?

> maybe you should compile it by yourself.
Is it possible only on Linux?

**Comment by higankanshi** [comment]
I have tested LibVlc 2.2.2 x64, with Sample, it work fine, I don't know what's your problem.

**Comment by Divaite** [comment]
Looks like I missed something or forgot to copy plugins, now it works. Unfortunately there is another proble, we get AccessViolationException frequently. Looks like there is opened issue for that, so you can close this thread, thanks for the help.
