### ISSUE TITLE
Grey screen when connecting to RTSP stream

### ISSUE THREAD

**Issue by DrAquArium** [higankanshi/xZune.Vlc#86]
Video is filled with grey blocks for several seconds when RTSP stream being connected. Video will eventually be back to normal. VLC player works totally fine with the same stream. It looks like that xZune.Vlc tries to play network video before getting the key frame.

**Comment by higankanshi** [comment]
Ummm, some video data wad lost when transfering, I'm not sure, maybe you can use TCP connect.
