### ISSUE TITLE
app is not responding after BeginStop

### ISSUE THREAD

**Issue by mshumilov** [higankanshi/xZune.Vlc#87]
1. the app stops responding always if BeginStop called from UI thread.
2. I have StateChanged / PositionChanged handlers and calls "VlcMediaPlayer.CanPlay" or "Position" from there. And the app stops responding often after BeginStop called. When I'm trying to stop the app in the debug mode, it shows me that it's running "VlcMediaPlayer.CanPlay" or "Position" code. And UI thread is completely blocked with it.

**Comment by higankanshi** [comment]
Ummm, I try to fix it, you can try the new code.

If it has no problem, I will update the Nuget Packages.

**Comment by mshumilov** [comment]
still the same. I've got Vlc.Wpf.Sample and moved ProgressBar.Value binding to the code:
```
            Player.PositionChanged += (sender, args) =>
            {
                for (var i = 0; i < 20; i++)
                    ProgressBar.Value = Player.Position;
            };
```
Then run the app, fill the path field and clicking to Load button several times. The app is freezing on VlcMediaPlayer, line 543: return _getPositionFunction.Delegate(InstancePointer);

Also, one time on: _stopFunction.Delegate(InstancePointer);

**Comment by mshumilov** [comment]
I've check you are using BeginInvoke in BeginStop. But BeginInvoke does not garantee its running in non UI thread. I'm not sure. but prob it's the reason.

**Comment by mshumilov** [comment]
The problem is not always happens.

Also I've tried to use Task.Run(() => Player.Stop) instead of BeginStop, but still the same issue.
I've tried to use Player.Dispose() instead of Stop, but still the same result.

So, to fix it, I've wrapped all calls to the player with the check dispose is not requested.

**Comment by Bruce198661** [comment]
Hi,
Maybe I resolved this bug.
Only one line of code added at xZune.Vlc.Wpf\VlcPlayer.cs  Line 413.
As bellow,
 public void Stop()
        {
            _isStopping = true;
            VlcMediaPlayer.Stop();
            VlcMediaPlayer.Media = null;  // I add this,and resolved.
            Dispatcher.BeginInvoke(DispatcherPriority.Normal, new Action(() => { VideoSource = null; }));
            _isStopping = false;
        }


Hope can help some one.

**Comment by Bruce198661** [comment]
Hi,

You should add some code at xZune.Vlc.Wpf\VlcPlayer.cs line 410 as bellow:

public void Stop()
        {
            _isStopping = true;
            VlcMediaPlayer.Media = null;
            VlcMediaPlayer.Stop();
            
            Dispatcher.BeginInvoke(DispatcherPriority.Normal, new Action(() => { VideoSource = null; }));
            _isStopping = false;
        }

I tried many times,and didn't occur any bugs.

Hope can help you.

**Comment by Bruce198661** [comment]
Hi,
    I also encountered this problem.
    Anyone resolved this issue?

**Comment by mshumilov** [comment]
How I solve it for the moment, to be sure Stop or Dispose are not called with other player calls. Use lock for all dispose and stop calls:
```
                lock (_lockPlayerInitialize)
                {
                    if (_player != null)
                    {
                        _player.Dispose();
                    }
                }
```

Then wrap all player calls with :
```
        private void SkipOnInitLock(Action action)
        {
            if (!Monitor.TryEnter(_lockPlayerInitialize))
                return;
            try
            {
                action.Fire();
            }
            finally
            {
                Monitor.Exit(_lockPlayerInitialize);
            }
        }
```

Then use:
`SkipOnInitLock(() => _lastPlaylistItemPlayed.Length = _player.Length);`

**Comment by higankanshi** [comment]
I have no Internet now, maybe I will try to fix it on next week.

**Comment by Divaite** [comment]
Hi.

Eventually I had to download sources and did some modifications. The major one is destroying old VlcMediaPlayer before opening a new media in VlcPlayer. Now it works without any issues, but I'm not sure how good this solution is.

**Comment by higankanshi** [comment]
You can try the new multi-thread VlcPlayer control.
