### ISSUE TITLE
too many state changes when opening files

### ISSUE THREAD

**Issue by Steinerline** [higankanshi/xZune.Vlc#88]
My Code looks like this:
`VLCPlayer.StateChanged += StateChangedHandler;`
`VLCPlayer.LoadMediaWithOptions(_VIDEO_PATH, new String[] { ":avcodec-hw=dxva2" });`
            `VLCPlayer.Play();`
The StateChangedHandler in this case prints the string that comes with the MediaState. 
Now, if i run this, it gives me this output:
All of this happens in about 2 seconds, without me pressing anything.
**
VideoWindow state: Opening
VideoWindow state: Opening
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
VideoWindow state: Playing
**
This then crashes my player about 75% of the time, but i think that has to do with the hardware acceleration. If i run it without hardware acceleration, it doesnt crash but the output is the same.
My question is: do you know why i have the change to Opening twice? i think the many Playings are a result of opening twice simultaneously. 

Also, this only happens with your new Nuget package, i used the old one until i needed the new load function with option and there i did not get this problem. is this normal maybe?

**Comment by higankanshi** [comment]
I have changed StateChanged event, you can try the new event.
