### ISSUE TITLE
DVD movie chapter support

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#9]
Most DVD movies consist of multiple chapters ... There needs to be a list of all chapters and a property to set/get the current chapter.

**Comment by sepehr1014** [comment]
We also need "Return to DVD menu" and "Return to title menu" options.

**Comment by higankanshi** [comment]
Chapter support is easy to add.
but, "Return to DVD menu" and "Return to title menu", I don't kown how to do it.

**Comment by sepehr1014** [comment]
VLC Media Player has "Title" and "Chapters" in its playback menu. You may be able to use Title for the menus.

**Comment by sepehr1014** [comment]
Any updates on this matter?

**Comment by higankanshi** [comment]
Ummm...I would add it on this weekend.Maybe...

**Comment by higankanshi** [comment]
I add "Title" and "Chapter" properties.
