### ISSUE TITLE
Video size displayed is wrong because of VideoTrack not found

### ISSUE THREAD

**Issue by mshumilov** [higankanshi/xZune.Vlc#90]
I have a dvd vob file and it's played with wrong ratio. I've checked you have VideoLockCallback method in VlcPlayer.Events.cs to determine the size. With the line `var videoMediaTracks = tracks.TakeWhile(t => t is VideoTrack).Select(t => t as VideoTrack).ToList();`

But in my video I have audio track first, and video track as the second element. So, videoMediaTracks is null always, so video is not resized.

I've changed it to `var videoMediaTracks = tracks.OfType<VideoTrack>().ToList();` and it works fine now.

**Comment by mshumilov** [comment]
let me create pull request for it

**Comment by higankanshi** [comment]
Thanks for your contribution.
