### ISSUE TITLE
Will not Play if Uri string have spaces or unicode file name

### ISSUE THREAD

**Issue by anhlunnhaque** [higankanshi/xZune.Vlc#92]
I think there's a bug when trying to play from Uri where the string to the file have spaces in it and/or is unicode text. I've tested and verified the below code.

_player.BeginStop(() =>
{
Uri.TryCreate("http://localhost:8091/test/testtest2.avi", UriKind.Absolute, out uri); <-- This works
Uri.TryCreate("http://localhost:8091/test/test   test2.avi", UriKind.Absolute, out uri); <--Will not play. Spaces in the file name. 
_player.LoadMedia(uri);
_player.Play();
});

Thanks.

**Comment by higankanshi** [comment]
I have try some Unicode char like Chinese, it work fine, but I found spaces have some problem with it, I have fixed it now, you can have a try.
