### ISSUE TITLE
'Initialization of 'xZune.Vlc.Wpf.VlcPlayer' threw an exception

### ISSUE THREAD

**Issue by armandvanderwalt** [higankanshi/xZune.Vlc#93]
Hi,

I am getting this error when using the plugin.

The inner exception:  模块文件不存在:<PATH>\\LibVlc\\libvlccore.dll

Use:
<wpf:VlcPlayer xmlns:wpf="clr-namespace:xZune.Vlc.Wpf;assembly=xZune.Vlc.Wpf" x:Name="vlcPlayer"/>

What can be the cause of this issue

**Comment by higankanshi** [comment]
Are you check your libvlc.dll and libvlccore.dll in this path?
