### ISSUE TITLE
Question about options

### ISSUE THREAD

**Issue by JohnnyPhoton** [higankanshi/xZune.Vlc#94]
Hi,
Nice Package, thanks!
From other things I've read on here LoadMediaWithOptions should work but I'm missing something. I'm using a slight modification to your example code...

string[] options = { "--vout-filter=transform", "--transform-type=vflip" };
Player.LoadMediaWithOptions(uri, options);

If I run VLC with these command line args, the video plays upside down but I can not get the example code to do it. Am I missing something? Using net 4.0 and VS 2010.

Thanks

**Comment by higankanshi** [comment]
Maybe usage of options in LoadMediaWithOptions has some differences, like #82.

I an not sure, if it still not work, maybe you can ask developer of VLC on [The VideoLAN Forums](https://forum.videolan.org/viewforum.php?f=32).

**Comment by JohnnyPhoton** [comment]
Didn't have much time to look at it lately but unlike #82 I don't think any options are working. I tried variations on flipping, trying a marque, and playing in grayscale and none seemed to work. If I have more time later I will look into it but I just thought I'd let you know what I found out.I will be doing some other testing with the lib later as well.
