### ISSUE TITLE
audio / video frames callback

### ISSUE THREAD

**Issue by roman-minyaylov** [higankanshi/xZune.Vlc#96]
Hi

I want to use VLC as a framegrabber for local files or RTSP and need 2 events for video and audio streams with frames in RGB(YUV)/PCM format.

Is it real? I think it's real for video because you have WPF wrapper but, is it possible to have the same for audio?

**Comment by higankanshi** [comment]
Yes, you can do it with xZune.Vlc.VlcMediaPlayer.
You can set video callback with VlcMediaPlayer.SetVideoCallback().
Also set audio callback with VlcMediaPlayer.SetAudioCallback().

**Comment by roman-minyaylov** [comment]
Thank you!

I can see SetAudioCallback but not SetVideoCallback. Is it SetVideoDecodeCallback?

**Comment by higankanshi** [comment]
Yes, you can see code of VlcPlayer control.

**Comment by roman-minyaylov** [comment]
Great, I got video callback and uncommented audio callbacks in WPF module to check usage, so, all ok now.

I think we can close this ticket. 

Just small question - is x64 libVLC supported?

**Comment by higankanshi** [comment]
Yes, we support x64 libVLC, but I changed some code this day, if it have any bugs with x64, please let me know.

**Comment by roman-minyaylov** [comment]
Not checked x64 yet, just asked.

I have another issue with video callback - no pts value, I need timestamps and don't see how to get them. For live streams that's only way to get frame time correctly.

Audio callbacks have timestamps, video callbacks not.

**Comment by higankanshi** [comment]
Yes, video callback has no timestamp.
I think there are one way to do it. Get the time property in callback. It is not a perfect way.
LibVlc does not provide it.

**Comment by roman-minyaylov** [comment]
What do you think, is it real to change libVLC code to add it? Right now it's looking that guys want to have solid library that play video by handle and callback way not implemented normally.

My real task is pushing frames to DirectShow filter with correct timestamps, that's a big problem for RTSP cams that can drop frames and so on.

**Comment by higankanshi** [comment]
I'm not sure, but I think you can go to the [The VideoLAN Forums](https://forum.videolan.org/viewforum.php?f=32) and ask developer of VLC abuout it.

**Comment by roman-minyaylov** [comment]
Thank you.
