### ISSUE TITLE
Visual Studio stops responding - Add the VlcPlayer Control

### ISSUE THREAD

**Issue by ORRNY66** [higankanshi/xZune.Vlc#97]
Hello,
I encountered a problem in the current version xZune.Vlc (16.3.28). When I want to add to your XAML Vlc Player Control and then compile the project and all of a sudden Visual Studio stops responding. I do not know where it would be a mistake. Thanks a lot

` <Grid>  
   <wpf:VlcPlayer x:Name="vlcPlayer" />
  </Grid>`

**Comment by higankanshi** [comment]
Ummm, No idea with it, can you compile the xZune.Vlc.Wpf.Sample?

**Comment by ORRNY66** [comment]
VLC Player Control goes to embed only through code-behind and not through XAML. And today, I ran into another problem the video image is not resized to fit the window

http://i.imgur.com/ruvH8wz.gifv

`       VlcPlayer Player = new VlcPlayer();
        public MainWindow()
        {
            InitializeComponent();
            Player.SetValue(Canvas.ZIndexProperty, -1);
            Player.EndBehavior = EndBehavior.Repeat;
            LayoutParent.Children.Add(Player);
        }`

**Comment by higankanshi** [comment]
Yes, I found this issue too, and I am trying to fix it.

**Comment by higankanshi** [comment]
I have found the result.
The MeasureOverride of ThreadSeparatedControlHost have some miss.
```CSharp
protected override System.Windows.Size MeasureOverride(System.Windows.Size constraint)
{
    var uiSize = new System.Windows.Size();

    if (TargetElement != null)
    {
        TargetElement.Dispatcher.Invoke(DispatcherPriority.Normal,
            new Action(() => TargetElement.Measure(constraint)));
        uiSize = TargetElement.DesiredSize;
    }

    return uiSize;
}
```

**Comment by higankanshi** [comment]
I have fix it in dev branch, if there are no bugs with it, I will update the nugget and release.
